var getRequestParamList=function(){var a=decodeURIComponent(location.search),b={};if(-1!=a.indexOf("?"))for(var a=a.substr(1).split("&&"),c=0;c<a.length;c++){var d=a[c].split("=");b[d[0]]=d[1]}return b},findIEVersion=function(){var a=navigator.appVersion;return-1<a.indexOf("compatible")&&-1<a.indexOf("MSIE")?(/MSIE (\d+\.\d+);/.test(a),parseFloat(RegExp.$1)):!1},getOSPlatformType=function(){var a=navigator.platform,b="";if(-1<a.indexOf("Windows")||-1<a.indexOf("Win"))b="windows";else if(-1<a.indexOf("Mac")||
-1<a.indexOf("mac"))b="mac";else if(-1<a.indexOf("Linux")||-1<a.indexOf("linux"))b="linux";return b},getBrowserType=function(){var a="",b=navigator.userAgent;-1<b.indexOf("Edge")||-1<b.indexOf("MSIE")?browse_type="ie":-1<b.indexOf("Firefox")?a="firefox":-1<b.indexOf("Chrome")?a="chrome":-1<b.indexOf("Safari")&&(a="safari");return a};function titleCase2(a){return a.toLowerCase().replace(/\b([\w|']+)\b/g,function(a){return a.replace(a.charAt(0),a.charAt(0).toUpperCase())})}ALM={};
var FILE_SERVER_IP_ADDRESS="202.120.143.190";ALM.STATIC_FILE_ROOT_PATH="http://"+FILE_SERVER_IP_ADDRESS+":8124/";ALM.MUT_RESULT_PATH=ALM.STATIC_FILE_ROOT_PATH+"/result/";ALM.HEATMAP_PATH=ALM.STATIC_FILE_ROOT_PATH+"/heatmap/";ALM.DRUGBANK_PATH=ALM.STATIC_FILE_ROOT_PATH+"/drugbank/";ALM.RESULT_PDB_ROOT_PATH=basePath+"/ALD/module/result_file/pdb_file/";ALM.RESULT_EXAMPLE_PDB_PATH=basePath+"/ALD/module/result_file/pdb_file/example/";ALM.RESULT_JOB_PDB_PATH=basePath+"/ALD/module/result_file/pdb_file/job/";
ALM.FILE_EXT={maf:"1",annovar:"2",tsv:"3"};
ALM.JOB_STATUS_LIST=[{job_step:"1",job_status:"2",status:"Job Started. Begin calculating"},{job_step:"1",job_status:"3",status:"Mutations has been mapped to the proteins"},{job_step:"2",job_status:"2",status:"Start mapping to the functional sites"},{job_step:"2",job_status:"3",status:"Mutations has been mapped to the functional sites. finished"},{job_step:"1",job_status:"9",status:"Error. No mutations mapped to the deposited proteins"},{job_step:"2",job_status:"10",status:"Error. No mutations mapped to the functional sites"},
{job_step:"1",job_status:"11",status:"Calculation Error"},{job_step:"2",job_status:"11",status:"Calculation Error"}];ALM.genJobStatusText=function(a,b){for(var c="",d=0;d<ALM.JOB_STATUS_LIST.length;d++){var e=ALM.JOB_STATUS_LIST[d];a==e.job_step&b==e.job_status&&(c=e.status)}Aciss3.isEmpty(c)&&(c="");return c};
ALM.scoreRenderer=function(a,b,c,d){a="";a=Aciss3.isEmpty(b)?Aciss3.parseTbCell(b):(new Number(b)).toFixed(3);return"<p style='display:block;width:80px;overflow:hidden;white-space: nowrap;text-overflow: ellipsis;'>"+a+"</p>"};
ALM.siteTypeRenderer=function(a,b,c,d){a="";return a=Aciss3.isEmpty(b)?Aciss3.parseTbCell(b):{"orthosteric site":"Orthosteric","potential allosteric site":"Allosteric (potential)","allosteric site":"Allosteric","Allosteric site":"Allosteric","Orthosteric site":"Orthosteric","Allosteric (potential) site":"Allosteric (potential)"}[b]+" site"};
ALM.addFavoriteAction=function(a,b){if(window.external&&"addFavorite"in window.external)window.external.addFavorite(a,b);else if(window.sidebar&&window.sidebar.addPanel)window.sidebar.addPanel(a,b);else{if(window.opera&&window.print)return this.title=b,!0;alert("Press "+(-1!=navigator.userAgent.toLowerCase().indexOf("mac")?"Command/Cmd":"CTRL")+" + D to bookmark this page.")}};ALM.basePanel=function(){this.init.apply(this,arguments)};
ALM.basePanel.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.id=a;Aciss3[this.id]=this;this._initPanelMainDiv()},_initPanelMainDiv:function(){var a=this.main_div,b=this.title,c=this.shown,d=$('<div class="panel panel-default"></div>'),e=a+"_panel_title_div",h=$('<div class="panel-heading"></div>'),g=$('<span id="'+e+'" style="display:inline-block;"></span>'),k=$('<span class="glyphicon glyphicon-chevron-down panel_collapsible" style="color:#000000;cursor:pointer;display:inline-block;float:right;"></span>'),
f=a+"_panel_body_div";this.panel_body_div_id=f;var l=$('<div class="panel-body" id="'+f+'"></div>');h.append(g).append(k);g=this.title_renderer;d.append(h).append(l);$("#"+a).append(d);a=this.content_renderer;Aciss3.isEmpty(g)?$("#"+e).html("<h4><b>"+b+"</b></h4>"):g(e,b);Aciss3.isEmpty(a)||a(f);k.on("click",function(){$(this).hasClass("glyphicon-chevron-down")?$(this).removeClass("glyphicon-chevron-down").addClass("glyphicon-chevron-right"):$(this).hasClass("glyphicon-chevron-right")&&$(this).removeClass("glyphicon-chevron-right").addClass("glyphicon-chevron-down");
l.toggle()});!0==c?$("#"+f).show():$("#"+f).hide()},hide:function(){$(this).removeClass("glyphicon-chevron-down").addClass("glyphicon-chevron-right");$("#"+this.panel_body_div_id).hide()},show:function(){$(this).removeClass("glyphicon-chevron-right").addClass("glyphicon-chevron-down");$("#"+this.panel_body_div_id).show()},refresh:function(){var a=this.content_renderer,b=this.panel_body_div_id;Aciss3.isEmpty(a)||a(b)}};
