Aciss3={};var validatePostiveFloat=function(a){var b=$("#"+a).val();if(!Aciss3.isEmpty(b)&&0>b)return Aciss3.renderErrorInput(a),!1;Aciss3.renderCorrectInput(a);return!0};Aciss3.padZero=function(a,b){for(var c=a.toString().length;c<b;)a="0"+a,c++;return a};Aciss3.isNumber=function(a){var b=!1;return b=/^[0-9,-,.]+$/.test(a)};Aciss3.addDays=function(a,b){var c=a.split("/"),c=new Date(c[2],c[0]-1,c[1]);c.setDate(c.getDate()+b);return c.Format("MM/dd/yyyy")};
Aciss3.accAdd=function(a,b){var c,d,e,f;try{c=a.toString().split(".")[1].length}catch(g){c=0}try{d=b.toString().split(".")[1].length}catch(h){d=0}f=Math.abs(c-d);e=Math.pow(10,Math.max(c,d));0<f?(f=Math.pow(10,f),c>d?(a=Number(a.toString().replace(".","")),b=Number(b.toString().replace(".",""))*f):(a=Number(a.toString().replace(".",""))*f,b=Number(b.toString().replace(".","")))):(a=Number(a.toString().replace(".","")),b=Number(b.toString().replace(".","")));return(a+b)/e};
Number.prototype.add=function(a){return Aciss3.accAdd(a,this)};Date.prototype.Format=function(a){var b={"M+":this.getMonth()+1,"d+":this.getDate(),"h+":this.getHours(),"m+":this.getMinutes(),"s+":this.getSeconds(),"q+":Math.floor((this.getMonth()+3)/3),S:this.getMilliseconds()};/(y+)/.test(a)&&(a=a.replace(RegExp.$1,(this.getFullYear()+"").substr(4-RegExp.$1.length)));for(var c in b)RegExp("("+c+")").test(a)&&(a=a.replace(RegExp.$1,1==RegExp.$1.length?b[c]:("00"+b[c]).substr((""+b[c]).length)));return a};
Aciss3.accSub=function(a,b){var c,d,e;try{c=b.toString().split(".")[1].length}catch(f){c=0}try{d=a.toString().split(".")[1].length}catch(g){d=0}e=Math.pow(10,Math.max(c,d));return((b*e-a*e)/e).toFixed(c>=d?c:d)};Number.prototype.sub=function(a){return Aciss3.accSub(a,this)};
Aciss3.SHA256Module=function(){function a(a){return h(k(g(a),8*a.length))}function b(a,b){var c=g(a);16<c.length&&(c=k(c,8*a.length));for(var d=Array(16),e=Array(16),f=0;16>f;f++)d[f]=c[f]^909522486,e[f]=c[f]^1549556828;c=k(d.concat(g(b)),512+8*b.length);return h(k(e.concat(c),768))}function c(a){try{l}catch(b){l=0}for(var c=l?"0123456789ABCDEF":"0123456789abcdef",d="",e,f=0;f<a.length;f++)e=a.charCodeAt(f),d+=c.charAt(e>>>4&15)+c.charAt(e&15);return d}function d(a){try{p}catch(b){p=""}for(var c=
"",d=a.length,e=0;e<d;e+=3)for(var f=a.charCodeAt(e)<<16|(e+1<d?a.charCodeAt(e+1)<<8:0)|(e+2<d?a.charCodeAt(e+2):0),g=0;4>g;g++)c=8*e+6*g>8*a.length?c+p:c+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(f>>>6*(3-g)&63);return c}function e(a,b){var c=b.length,d=[],e,f,g,h,k=Array(Math.ceil(a.length/2));for(e=0;e<k.length;e++)k[e]=a.charCodeAt(2*e)<<8|a.charCodeAt(2*e+1);for(;0<k.length;){h=[];for(e=g=0;e<k.length;e++)if(g=(g<<16)+k[e],f=Math.floor(g/c),g-=f*c,0<h.length||
0<f)h[h.length]=f;d[d.length]=g;k=h}c="";for(e=d.length-1;0<=e;e--)c+=b.charAt(d[e]);d=Math.ceil(8*a.length/(Math.log(b.length)/Math.log(2)));for(e=c.length;e<d;e++)c=b[0]+c;return c}function f(a){for(var b="",c=-1,d,e;++c<a.length;)d=a.charCodeAt(c),e=c+1<a.length?a.charCodeAt(c+1):0,55296<=d&&56319>=d&&56320<=e&&57343>=e&&(d=65536+((d&1023)<<10)+(e&1023),c++),127>=d?b+=String.fromCharCode(d):2047>=d?b+=String.fromCharCode(192|d>>>6&31,128|d&63):65535>=d?b+=String.fromCharCode(224|d>>>12&15,128|
d>>>6&63,128|d&63):2097151>=d&&(b+=String.fromCharCode(240|d>>>18&7,128|d>>>12&63,128|d>>>6&63,128|d&63));return b}function g(a){for(var b=Array(a.length>>2),c=0;c<b.length;c++)b[c]=0;for(c=0;c<8*a.length;c+=8)b[c>>5]|=(a.charCodeAt(c/8)&255)<<24-c%32;return b}function h(a){for(var b="",c=0;c<32*a.length;c+=8)b+=String.fromCharCode(a[c>>5]>>>24-c%32&255);return b}function m(a,b){return a>>>b|a<<32-b}function k(a,b){var c=[1779033703,-1150833019,1013904242,-1521486534,1359893119,-1694144372,528734635,
1541459225],d=Array(64),e,f,g,h,k,l,p,A,y,t,B,E;a[b>>5]|=128<<24-b%32;a[(b+64>>9<<4)+15]=b;for(y=0;y<a.length;y+=16){e=c[0];f=c[1];g=c[2];h=c[3];k=c[4];l=c[5];p=c[6];A=c[7];for(t=0;64>t;t++)d[t]=16>t?a[t+y]:n(n(n(m(d[t-2],17)^m(d[t-2],19)^d[t-2]>>>10,d[t-7]),m(d[t-15],7)^m(d[t-15],18)^d[t-15]>>>3),d[t-16]),B=n(n(n(n(A,m(k,6)^m(k,11)^m(k,25)),k&l^~k&p),q[t]),d[t]),E=n(m(e,2)^m(e,13)^m(e,22),e&f^e&g^f&g),A=p,p=l,l=k,k=n(h,B),h=g,g=f,f=e,e=n(B,E);c[0]=n(e,c[0]);c[1]=n(f,c[1]);c[2]=n(g,c[2]);c[3]=n(h,
c[3]);c[4]=n(k,c[4]);c[5]=n(l,c[5]);c[6]=n(p,c[6]);c[7]=n(A,c[7])}return c}function n(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535}var l=0,p="",q=[1116352408,1899447441,-1245643825,-373957723,961987163,1508970993,-1841331548,-1424204075,-670586216,310598401,607225278,1426881987,1925078388,-2132889090,-1680079193,-1046744716,-459576895,-272742522,264347078,604807628,770255983,1249150122,1555081692,1996064986,-1740746414,-1473132947,-1341970488,-1084653625,-958395405,-710438585,
113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,-2117940946,-1838011259,-1564481375,-1474664885,-1035236496,-949202525,-778901479,-694614492,-200395387,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,-2067236844,-1933114872,-1866530822,-1538233109,-1090935817,-965641998];return{hex_sha256:function(b){return c(a(f(b)))},b64_sha256:function(b){return d(a(f(b)))},any_sha256:function(b,c){return e(a(f(b)),
c)},hex_hmac_sha256:function(a,d){return c(b(f(a),f(d)))},b64_hmac_sha256:function(a,c){return d(b(f(a),f(c)))},any_hmac_sha256:function(a,c,d){return e(b(f(a),f(c)),d)}}}();
Function.prototype.bind||(Function.prototype.bind=function(a){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var b=Array.prototype.slice.call(arguments,1),c=this,d=function(){},e=function(){return c.apply(this instanceof d?this:a,b.concat(Array.prototype.slice.call(arguments)))};this.prototype&&(d.prototype=this.prototype);e.prototype=new d;return e});
String.prototype.trim||function(){var a=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;String.prototype.trim=function(){return this.replace(a,"")}}();Aciss3.genEnumTypeCombo=function(a,b){var c={};c.module=a;new Aciss3.matchCombo(b+"_combo",{main_div:b,place_holder:"Select....",post_url:"/LoadEnum",submit_params:c,allow_fill:!1,req_type:"yes"})};
Aciss3.genEnumTypeComboByEnumClass=function(a,b){var c={};c.enum_class=a;new Aciss3.matchCombo(b+"_combo",{main_div:b,place_holder:"Select....",post_url:"/LoadEnumByEnumClass",submit_params:c,allow_fill:!1,req_type:"yes"})};Aciss3.isInteger=function(a){return/^\d+$/.test(a)?!0:!1};Aciss3.isPosInteger=function(a){return/^[0-9]*[1-9][0-9]*$/.test(a)?!0:!1};Aciss3.isFloat=function(a){return/^(-?\\d+)(\\.\\d+)?$/.test(a)?!0:!1};Aciss3.renderErrorInput=function(a){$("#"+a).addClass("error_input")};
Aciss3.renderCorrectInput=function(a){$("#"+a).removeClass("error_input")};
Aciss3.validateForm=function(a,b,c,d,e){var f=0;Aciss3.isEmpty(d)||(d=d.trim(),f=d.toString().length);var g=!0;"int"!=a||Aciss3.isInteger(d)?"pos_int"!=a||Aciss3.isPosInteger(d)?"float"!=a||Aciss3.isFloat(d)?"yes"==b&&Aciss3.isEmpty(d)?(Aciss3.renderErrorInput(e),g=!1):"yes"==b&&null!=c&&f<c?(Aciss3.renderErrorInput(e),g=!1):(Aciss3.renderCorrectInput(e),g=!0):null!=b&&"no"==b&&Aciss3.isEmpty(d)?(Aciss3.renderCorrectInput(e),g=!0):(Aciss3.renderErrorInput(e),g=!1):null!=b&&"no"==b&&Aciss3.isEmpty(d)?
(Aciss3.renderCorrectInput(e),g=!0):(Aciss3.renderErrorInput(e),g=!1):null!=b&&"no"==b&&Aciss3.isEmpty(d)?(Aciss3.renderCorrectInput(e),g=!0):(Aciss3.renderErrorInput(e),g=!1);return g};
Aciss3.initValidateForm=function(a){for(var b=$('form[name="'+a+'"]').find("input,select,textarea").not("[type=submit]"),c=0;c<b.length;c++)(function(){var a=b[c],e=a.getAttribute("id"),f=a.getAttribute("validationType"),g=a.getAttribute("reqType"),h=a.getAttribute("minLength");if(null!=f||null!=g||null!=h)$(a).val(),$("#"+e).on("blur",function(){var a=$("#"+e).val();Aciss3.validateForm(f,g,h,a,e)})})()};
Aciss3.validateFormBeforeSubmit=function(a){var b=[];a=$('form[name="'+a+'"]').find("input:visible,select:visible,textarea:visible").not("[type=submit]");for(var c=0;c<a.length;c++){var d=a[c],e=d.getAttribute("id"),f=d.getAttribute("validationType"),g=d.getAttribute("reqType"),d=d.getAttribute("minLength");if(null!=f||null!=g||null!=d){var h=$("#"+e).val();b.push(Aciss3.validateForm(f,g,d,h,e))}}return-1!=b.indexOf(!1)?!1:!0};
Aciss3.genGridTip=function(a){var b="You got "+a+" records by filters.";"ch"==LAN&&(b="\u68c0\u7d22\u5f97\u5230"+a+" \u6761\u6570\u636e\u3002");return b};Aciss3.genColumnShowName=function(a,b){if(void 0!=a[b]){var c=a[b][0];"ch"==LAN&&(c=a[b][1]);return c}return""};Aciss3.genColumnEnName=function(a,b){return void 0!=a[b]?a[b][0]:""};
Aciss3.renderNumberInput=function(a,b,c){var d=$("#"+a+"_div");a=$('<div class="input-group spinner" data-trigger="spinner"><input placeholder="Input a number" validationType="'+b+'" reqType="'+c+'" type="text" class="form-control" id="'+a+'">');b=$('<div class="input-group-addon">');b.append('<a onClick="NumberInputPlus(this)" class="spin-up" data-spin="up"><i class="fa fa-caret-up"></i></a>');b.append('<a onClick="NumberInputMinus(this)" class="spin-down" data-spin="down"><i class="fa fa-caret-down"></i></a>');
a.append(b);d.append(a)};Aciss3.isEmptyMolStr=function(a){return"Made By AcissWriter@TuXiong   \n\n  0  0  0  0  0  0            999 V2000\nM  END"==$.trim(a)?!0:!1};Aciss3.parseTbCell=function(a){return Aciss3.isEmpty(a)?"No info.":a};Aciss3.openUrlLink=function(a){location.href=a};Aciss3.isEmpty=function(a){if(void 0==a||null==a)return!0;a=a.toString();return""==a||"null"==a||"undefined"==a?!0:!1};Aciss3.resetEmptyString=function(a){return Aciss3.isEmpty(a)?"&nbsp":a};Aciss3.isUnsignedInteger=function(a){return/^[0-9]*[1-9][0-9]*$/.test(a)};
Aciss3.isFloat=function(a){return/^(-?\d+)(\.\d+)?$/.test(a)};Aciss3.isEmptyContentByIdList=function(a){for(var b=!0,c=0;c<a.length;c++){var d=$("#"+a[c]).val();if(void 0!=d&&null!=d&&""!=d.toString()){b=!1;break}}return b};Aciss3.popFormErrorNotify=function(){"ch"==LAN?alert("\u8bf7\u5148\u4fee\u6539\u586b\u5199\u9519\u8bef\u7684\u9879\uff08\u7ea2\u8272\u8fb9\u6846\uff09\uff01"):alert("Please correct the wrong field (red border)!")};
Aciss3.popSuccessNotify=function(){var a="Success";"ch"==LAN&&(a="\u64cd\u4f5c\u6210\u529f\uff01");Aciss3.popNotify(a)};Aciss3.popInfoNotify=function(a,b){LAN="ch";alert(b)};Aciss3.popErrorNotify=function(){LAN="ch";alert("\u64cd\u4f5c\u5931\u8d25\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5\uff01")};
Aciss3.popNotify=function(a,b){var c=$(window).height(),c=Math.floor(c/2),d="glyphicon glyphicon-ok-sign";void 0==b||null==b?b="success":"warning"==b||"danger"==b?d="glyphicon glyphicon-warning-sign":"info"==b&&(d="glyphicon glyphicon-info-sign");$.notify({message:"<b>"+a+"</b>",icon:d},{type:b,placement:{from:"top",align:"center"},offset:{y:c},delay:100})};Aciss3.getCmp=function(a){return Aciss3[a]};
var formatDatePlugin=function(){$(".form_date").datetimepicker({weekStart:1,todayBtn:1,autoclose:1,todayHighlight:1,startView:2,minView:2,forceParse:0})};
Aciss3.getEnumTypeValue=function(a){var b="Unknown";"gene_cloning"==a?b="Gene cloning":"target"==a?b="Target":"protein_reagent"==a?b="Protein reagent":"protein_reagent_pur"==a?b="Protein reagent (Purification)":"assay"==a?b="Assay":"assay_res"==a?b="Assay Batch Result":"fbdd"==a?b="FBDD":"stru"==a||"stru_mounting"==a||"stru_data"==a||"stru_deter"==a?b="Structure group":"reagent"==a?b="Reagent":"documents"==a?b="Documents":"sample"==a?b="Sample":"molecule"==a?b="Molecule":"enum"==a?b="Parameters":
"project"==a?b="Project":"notebook"==a?b="Notebook":"user"==a?b="User":"doc"==a?b="Document":"column"==a&&(b="Column");return b};Aciss3.sideToolbarMenu=function(a,b,c){this.main_menu=a;this.children_menu_list=b;this.children_menu_href=c};
Aciss3.sideToolbarMenu.prototype={addMenu:function(a){var b=this.main_menu+"_collapse",c=$('<div class="panel panel-default">'),d=$('<div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#'+b+'">'+this.main_menu+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></h4></div>"),e=$('<div id="'+b+'" class="panel-collapse collapse"></div>');if("in"==a)e=$('<div id="'+b+'" class="panel-collapse collapse in"></div>');else{a=window.location.href;for(var f=0;f<
this.children_menu_href.length;f++)0<=a.indexOf(this.children_menu_href[f])&&(e=$('<div id="'+b+'" class="panel-collapse collapse in"></div>'))}b=$('<div class="panel-body"></div>');for(a=0;a<this.children_menu_list.length;a++)b.append("<p><a href="+path+this.children_menu_href[a]+' style="cursor:pointer;color:#0078d7;"><b>'+this.children_menu_list[a]+"</b></a></p>");e.append(b);c.append(d);c.append(e);$("#page_side_toolbar").append(c)}};Aciss3.progressTab=function(){this.init.apply(this,arguments)};
Aciss3.progressTab.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.initFrame();Aciss3[this.Id]=this},initFrame:function(){var a=this.tab_div,b="+ New Progress",c="+ New Query";"ch"==LAN&&(b="+ \u65b0\u7684\u8fdb\u5ea6\u9879",c="+ \u65b0\u7684\u63d0\u95ee");b=$('<a class="btn btn-default" style="margin-top:20px;margin-bottom:20px;" type="button"><span style="font-weight:bold;color:#0078d7;">'+b+"</span></a>");a.append(b);this.genProgressTable();c=$('<a class="btn btn-default" style="margin-top:20px;margin-bottom:10px;" type="button"><span style="font-weight:bold;color:#0078d7;">'+
c+"</span></a><br />");a.append(c);this.genQueryTable();b.on("click",this.popNewProgressWin.bind(this));c.on("click",this.popNewQueryWin.bind(this))},submitNewQuery:function(){var a=this.main_id,b=this.module,c=$("#register_query_from").val(),d=$("#register_query_txt").val();if(Aciss3.isEmpty(c))alert("Please fill the From field!");else if(Aciss3.isEmpty(d))alert("Please fill the Query field!");else{var e={};e.query_from=c;e.query_content=d;e.query_module=b;e.related_id=a;var f=this;$.post(path+"/SubmitNewQuery",
e,function(a){a.success?(Aciss3.popSuccessNotify(),f.query_modal.modal("hide"),f.query_start=0,f.refreshQueryTable()):Aciss3.popErrorNotify()})}},popNewQueryWin:function(){var a="+ New Query",b="Submit",c="Cancel",d="From",e="Query";"ch"==LAN&&(a="+ \u65b0\u7684\u63d0\u95ee",b="\u63d0\u4ea4",c="\u53d6\u6d88",d="\u63d0\u95ee\u4eba",e="\u95ee\u9898\u5185\u5bb9");var f=$('<div class="modal fade new_query_modal">'),a=$('<div class="modal-header"><a class="close" data-dismiss="modal">&times;</a><p style="font-size:15px;"><b>'+
a+"</b></p></div>"),g=$('<div class="modal-body"><form></form></div>');g.append('<div class="row" style="margin-top:10px;"><div class="col-xs-2 font-gray">'+d+'<span style="color:red;">*</span>:</div><div class="col-xs-10 font-gray"><input type="text" class="form-control" id="register_query_from"></div></div>');g.append('<div class="row" style="margin-top:10px;"><div class="col-xs-2 font-gray">'+e+'<span style="color:red;">*</span>:</div><div class="col-xs-10 font-gray"><textarea id="register_query_txt" class="col-xs-10 form-control" rows="5" placeholder="No more than 500 words."></textarea></div></div>');
d=$('<div class="modal-footer" style="text-align:center;">');b=$('<button id="submit_query_button" class="btn btn-primary" type="button">'+b+"</button>");c=$('<button id="cancel_query_button" class="btn btn-default" type="button" data-dismiss="modal">'+c+"</button>");b.on("click",this.submitNewQuery.bind(this));d.append(b);d.append(c);f.append(a);f.append(g);f.append(d);this.query_modal=f;f.modal();f.on("hidden.bs.modal",function(){$(this).data("bs.modal",null);f.remove()})},submitNewProgress:function(){var a=
this.Id,b=this.main_id,c=this.module,d=$("input[name='progress_status_"+a+"']:radio:checked").val(),e=Aciss3.getCmp("register_progress_step_combo_"+a).getValue(),f=Aciss3.getCmp("register_progress_date_input_"+a).getValue(),a=$("#register_progress_txt_"+a).val();"delivery"==d&&(e=0);if("running"==d&&Aciss3.isEmpty(e))Aciss3.popInfoNotify("Please select progress step!","\u8bf7\u9009\u62e9\u8fdb\u5ea6\u6b65\u9aa4\uff01");else if(Aciss3.isEmpty(f))Aciss3.popInfoNotify("Please select progress date!",
"\u8bf7\u9009\u62e9\u8fdb\u5ea6\u65e5\u671f\uff01");else if(Aciss3.isEmpty(a))Aciss3.popInfoNotify("Please fill progress step comments!","\u8bf7\u586b\u5199\u8fdb\u5ea6\u5907\u6ce8\uff01");else{d={};d.progress_step_enum_id=e;d.progress_date=f;d.progress_step_comments=a;d.progress_module=c;d.related_id=b;var g=this;$.post(path+"/SubmitNewProgress",d,function(a){a.success?(Aciss3.popSuccessNotify(),g.progress_modal.modal("hide"),g.progress_start=0,g.refreshProgressTable()):alert("Submit failure. Please try later again.")})}},
popNewProgressWin:function(){var a=this.Id,b=this.module,c="+ New Progress",d="Status",e="Progress",f="Date",g="Detail",h="Submit",m="Cancel";"ch"==LAN&&(c="+ \u65b0\u7684\u8fdb\u5ea6\u9879",d="\u72b6\u6001",e="\u8fdb\u5ea6\u9879",f="\u8fdb\u5ea6\u65e5\u671f",g="\u8be6\u60c5",h="\u63d0\u4ea4",m="\u53d6\u6d88");var k=$('<div class="modal fade new_progress_modal">'),c=$('<div class="modal-header"><a class="close" data-dismiss="modal">&times;</a><p style="font-size:15px;"><b>'+c+"</b></p></div>"),n=
$('<div class="modal-body"><form></form></div>'),l=$('<div class="row" style="margin-top:10px;">');l.append('<div class="col-xs-2 font-gray">'+d+'<span style="color:red;">*</span>:</div>');l.append('<div class="col-xs-3"><input type="radio" name="progress_status_'+a+'" value="running" checked=true>&nbsp;Running</div>');l.append('<div class="col-xs-3"><input type="radio" name="progress_status_'+a+'" value="delivery">&nbsp;Delivery</div>');n.append(l);d=$('<div class="row" style="margin-top:10px;">');
d.append('<div class="col-xs-2 font-gray">'+e+'<span style="color:red;">*</span>:</div>');e=$('<div class="col-xs-4 font-gray" id="register_progress_step_'+a+'"></div>');d.append(e);d.append('<div class="col-xs-2 font-gray">'+f+'<span style="color:red;">*</span>:</div>');f=$('<div class="col-xs-4 font-gray" id="register_progress_date_'+a+'"></div>');d.append(f);n.append(d);n.append('<div class="row" style="margin-top:10px;"><div class="col-xs-2 font-gray">'+g+'<span style="color:red;">*</span>:</div><div class="col-xs-10"><textarea id="register_progress_txt_'+
a+'" class="col-xs-12 form-control" rows="3" placeholder="No more than 100 words.">/</textarea></div></div>');g=$('<div class="modal-footer" style="text-align:center;"></div>');h=$('<button class="btn btn-primary" type="button">'+h+"</button>");m=$('<button class="btn btn-default" type="button" data-dismiss="modal">'+m+"</button>");h.on("click",this.submitNewProgress.bind(this));g.append(h);g.append(m);k.append(c);k.append(n);k.append(g);this.progress_modal=k;k.on("shown.bs.modal",function(){var c=
{};c.module=b;new Aciss3.matchCombo("register_progress_step_combo_"+a,{main_div:"register_progress_step_"+a,place_holder:"Select Step",post_url:"/LoadEnum",submit_params:c});new Aciss3.dateInput("register_progress_date_input_"+a,{main_div:"register_progress_date_"+a});$("input[name='progress_status_"+a+"']").on("change",function(){var b=$("input[name='progress_status_"+a+"']:radio:checked").val();"delivery"==b&&Aciss3.getCmp("register_progress_step_combo_"+a).disable();"running"==b&&Aciss3.getCmp("register_progress_step_combo_"+
a).enable()})});k.on("hidden.bs.modal",function(){$(this).data("bs.modal",null);k.remove()});k.modal()},genProgressTable:function(){var a=this.tab_div,b=$('<table id="progress_table_'+this.main_id+'" class="table">');a.append(b);this.loadProgressData(b);var b=$('<div class="text-right"></div>'),c=$('<button class="btn btn-default" type="button"><span class="glyphicon glyphicon-chevron-down"></span></button>');c.on("click",this.loadMoreProgressData.bind(this));b.append(c);a.append(b)},refreshProgressTable:function(){var a=
$("#progress_table_"+this.main_id);a.empty();this.loadProgressData(a)},loadMoreProgressData:function(){var a=this.main_id;this.progress_start+=5;a=$("#progress_table_"+a);this.loadProgressData(a)},deleteProgressAction:function(a){var b={},c=this;b.progress_id=a;$.post(path+"/deleteProgress",b,function(a){a.success&&(Aciss3.popNotify("Success!"),c.refreshProgressTable())})},deleteProgress:function(a){var b=this,c="Delete it?";"ch"==LAN&&(c="\u786e\u8ba4\u5220\u9664\u5417\uff1f");$.prompt("<span style='font-size:14px;'>"+
c+"</span>",{title:"",buttons:{Yes:!0,No:!1},submit:function(c,e,f,g){e&&b.deleteProgressAction(a)}})},loadProgressData:function(a){var b=this.main_id,c=this.module,d=this.progress_start,e=this.progress_limit;0==a.find("th").length&&("ch"==LAN?a.append("<th>\u8fdb\u5ea6\u9879</th><th>\u8fdb\u5ea6\u65e5\u671f</th><th>\u8be6\u60c5</th><th>\u63d0\u4ea4\u4eba</th><th>&nbsp;</th>"):a.append("<th>Progress Step</th><th>Progress Date</th><th>Details</th><th>Add User</th><th>&nbsp;</th>"));var f={};f.progress_module=
c;f.related_id=b;f.start=d;f.limit=e;var g=this;$.post(path+"/ProgressBrowse",f,function(b){if(b.success){var c=b.data;b=b.totalCount;if(0!=d&&b<=d)g.progress_start-=5,"ch"==LAN?Aciss3.popNotify("\u6ca1\u6709\u66f4\u591a\u7684\u8fdb\u5ea6\u6570\u636e\u4e86\uff01"):Aciss3.popNotify("No more progress!");else for(b=0;b<c.length;b++){var e=c[b],f=e.progress_step,l=e.progress_id,p=e.progress_step_comments,q=e.register_user_name,r=e.progress_date,r=r.split(" ")[0],e=$("<tr>");e.append('<td width="20%">'+
f+'</td><td width="15%">'+r+'</td><td width="45%">'+p+'</td><td width="15%">'+q+"</td>");f=$('<td width="5%" class="progress_button"><span class="glyphicon glyphicon-trash" style="cursor:pointer;"></span></td>');f.on("click",function(a){return function(){g.deleteProgress(a)}}(l));e.append(f);a.append(e)}}})},refreshQueryTable:function(){var a=$("#query_table_"+this.main_id);a.empty();this.loadQueryData(a)},genQueryTable:function(){var a=this.tab_div,b=$('<div id="query_table_'+this.main_id+'">');
a.append(b);this.loadQueryData(b);var b=$('<br /><div class="text-right"></div>'),c=$('<button class="btn btn-default" type="button"><span class="glyphicon glyphicon-chevron-down"></span></button>');c.on("click",this.loadMoreQueryData.bind(this));b.append(c);a.append(b)},deleteQueryAction:function(a){var b=this,c={};c.query_id=a;$.post(path+"/DeleteQuery",c,function(a){a.success&&(Aciss3.popNotify("Success!"),b.refreshQueryTable())})},deleteQuery:function(a){var b=this;$.prompt("<span style='font-size:14px;'>Delete it?</span>",
{title:"",buttons:{Yes:!0,No:!1},submit:function(c,d,e,f){d&&b.deleteQueryAction(a)}})},loadMoreQueryData:function(){var a=$("#query_table_"+this.main_id);this.query_start+=5;this.loadQueryData(a)},loadQueryData:function(a){var b=this.main_id,c=this.query_start,d=this.query_limit,e={};e.query_module=this.module;e.related_id=b;e.start=c;e.limit=d;var f=this;$.post(path+"/QueryBrowse",e,function(b){if(b.success){var d=path+"/img/temp_img.svg",e=b.data;b=b.totalCount;if(0!=c&&b<=c)"ch"==LAN?Aciss3.popNotify("\u6ca1\u6709\u66f4\u591a\u63d0\u95ee\u6570\u636e\u4e86\uff01"):
Aciss3.popNotify("No more query!"),f.query_start-=5;else for(b=0;b<e.length;b++){var k=e[b],n=k.query_date,l=k.query_id,p=k.query_content,q=k.query_user_name,r=k.reply_count,s=k.replyList,k=$('<div class="media"><div class="media-left media-top"><a href="#"><img class="media-object" src="'+d+'" alt="..."></a></div>'),u=$('<div class="media-body">'),w="Query from ";"ch"==LAN&&(w="\u63d0\u95ee\u4eba  ");n=$('<span class="media-heading" style="font-size:17px;font-weight:bold;color:#318dfd;">'+n+"<br />"+
w+" "+q+": "+p+"</span>");u.append(n);n=$("<div>");u.append(n);f.loadReplyData(n,s);s="+ New Reply";"ch"==LAN&&(s="+ \u65b0\u7684\u56de\u590d");s=$('<button class="btn btn-default" type="button"><span style="font-weight:bold;color:#0078d7;">'+s+"</span></button>");u.append(s);s.on("click",function(a,b){return function(){f.popNewReplyWin(a,b)}}(f.main_id,l));5<r&&(r="More...","ch"==LAN&&(r="\u67e5\u770b\u66f4\u591a..."),r=$('<button class="btn btn-default" type="button" style="margin-left:10px;"><span style="font-weight:bold;color:#0078d7;">'+
r+"</span></button>"),u.append(r),r.on("click",function(a,b){return function(){f.loadMoreReplyData(a,b)}}(n,l)));r=$('<button class="btn btn-default" type="button" style="margin-left:10px;"><span class="glyphicon glyphicon-trash"></span></button>');u.append(r);r.on("click",function(a){return function(){f.deleteQuery(a)}}(l));u.append('<br /><br /><div style="width:100%;border-bottom: 3px solid #dddddd;">&nbsp;</div>');k.append(u);a.append(k)}}})},loadMoreReplyData:function(a,b){var c=a.find("span.progress_button").length,
d={};d.query_id=b;d.start=c;d.limit=5;var e=this;$.post(path+"/LoadMoreQueryReply",d,function(b){if(b.success){var d=b.data;b=b.totalCount;0!=c&&b<=c?"ch"==LAN?Aciss3.popNotify("\u6ca1\u6709\u66f4\u591a\u6570\u636e\u4e86!"):Aciss3.popNotify("No more reply!"):e.loadReplyData(a,d)}})},deleteReplyAction:function(a){var b=this,c={};c.reply_id=a;$.post(path+"/DeleteQueryReply",c,function(a){a.success&&(Aciss3.popSuccessNotify(),b.refreshQueryTable())})},deleteReply:function(a){var b=this;$.prompt("<span style='font-size:14px;'>Delete it?</span>",
{title:"",buttons:{Yes:!0,No:!1},submit:function(c,d,e,f){d&&b.deleteReplyAction(a)}})},loadReplyData:function(a,b){for(var c=0;c<b.length;c++){var d=b[c],e=d.query_reply_id;a.append('<br /><span style="font-size:14px;line-height:25px;"><span class="label label-success" style="font-size:14px;">'+d.reply_user_name+"</span>&nbsp;&nbsp;</b>"+d.reply_content+"</span><br />"+d.reply_date+"&nbsp;&nbsp;");d=$('<span class="progress_button"><span class="glyphicon glyphicon-trash"></span></span>');a.append(d);
var f=this;d.on("click",function(a){return function(){f.deleteReply(a)}}(e));a.append('<p style="border-bottom:1px dotted #dddddd;"></p>')}0==a.find("span").length&&("ch"==LAN?a.append("<p>\u6682\u65f6\u6ca1\u6709\u56de\u590d\u3002</p>"):a.append("<p>No Reply.</p>"))},submitNewReply:function(a){var b=$("#register_query_reply_txt").val();if(Aciss3.isEmpty(b))"ch"==LAN?alert("\u8bf7\u586b\u5199\u56de\u590d\u5185\u5bb9!"):alert("Please fill the reply field!");else{var c={};c.reply_content=b;c.query_id=
a;var d=this;$.post(path+"/SubmitNewQueryReply",c,function(a){a.success&&(Aciss3.popSuccessNotify(),d.reply_modal.modal("hide"),d.refreshQueryTable())})}},popNewReplyWin:function(a,b){var c=this,d="Reply",e="Submit",f="Cancel";"ch"==LAN&&(d="\u56de\u590d\u5185\u5bb9",e="\u63d0\u4ea4",f="\u53d6\u6d88");var g=$('<div class="modal fade new_query_reply_modal">'),h=$('<div class="modal-header"><a class="close" data-dismiss="modal">&times;</a><p style="font-size:15px;"><b></b></p></div>'),m=$('<div class="modal-body"><form></form></div>');
m.append('<div class="row" style="margin-top:10px;"><div class="col-xs-3 font-gray">'+d+'<span style="color:red;">*</span>:</div><div class="col-xs-9"><textarea id="register_query_reply_txt"  class="col-xs-12 form-control" rows="3" placeholder="No more than 100 words."></textarea></div></div>');d=$('<div class="modal-footer" style="text-align:center;"></div>');e=$('<button class="btn btn-primary" type="button">'+e+"</button>");f=$('<button class="btn btn-default" type="button" data-dismiss="modal">'+
f+"</button>");e.on("click",function(){c.submitNewReply(b)});d.append(e);d.append(f);g.append(h);g.append(m);g.append(d);this.reply_modal=g;g.modal();g.on("hidden.bs.modal",function(){$(this).data("bs.modal",null);g.remove()})},clearPopModal:function(){this.query_modal=this.progress_modal=this.reply_modal=null}};Aciss3.baseGrid=function(){this.init.apply(this,arguments)};
Aciss3.baseGrid.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this._addGridTipBar();this._addTopPagingBar();this._initGridData();this._addBottomPagingBar();Aciss3[this.Id]=this},_addGridTipBar:function(){this.grid_tip_div=$('<div style="font-size:16px;color:#434a54;"></div>');$("#"+this.main_div).append(this.grid_tip_div)},setGridTip:function(a){this.grid_tip_div.empty();this.grid_tip_div.html(a)},resetGridTip:function(){this.grid_tip_div.empty()},_firstPage:function(){if(0==
this.start){var a="The current page is the first page.";"ch"==LAN&&(a="\u5f53\u524d\u9875\u5df2\u7ecf\u662f\u7b2c\u4e00\u9875\u3002");Aciss3.popNotify(a)}else this.start=0,this.now_page=1,a=this.submit_params,a.start=this.start,a.limit=this.page_size,this._loadGridData("no_init",a)},_prePage:function(){if(5<=this.start){this.start-=this.page_size;this.now_page-=1;var a=this.submit_params;a.start=this.start;a.limit=this.page_size;this._loadGridData("no_init",a)}else a="The current page is the first page.",
"ch"==LAN&&(a="\u5f53\u524d\u9875\u5df2\u7ecf\u662f\u7b2c\u4e00\u9875\u3002"),Aciss3.popNotify(a)},_nextPage:function(){if(this.start<this.total_count-this.page_size){this.start+=this.page_size;this.now_page+=1;var a=this.submit_params;a.start=this.start;a.limit=this.page_size;this._loadGridData("no_init",a)}else a="The current page is the last page.","ch"==LAN&&(a="\u5f53\u524d\u9875\u5df2\u7ecf\u662f\u6700\u540e\u4e00\u9875\u3002"),Aciss3.popNotify(a)},_lastPage:function(){if(this.start<this.total_count-
this.page_size){var a=this.total_count%this.page_size;0==a&&(a=this.page_size);this.start=this.total_count-a;this.now_page=Math.ceil(this.total_count/this.page_size);a=this.submit_params;a.start=this.start;a.limit=this.page_size;this._loadGridData("no_init",a)}else a="The current page is the last page.","ch"==LAN&&(a="\u5f53\u524d\u9875\u5df2\u7ecf\u662f\u6700\u540e\u4e00\u9875\u3002"),Aciss3.popNotify(a)},_jumpPage:function(a){var b=this.page_size;"13"==(a.keyCode?a.keyCode:a.which)&&(a=$("#"+a.currentTarget.id).val(),
Aciss3.isUnsignedInteger(a)?parseInt(a)>this.page_count?"ch"==LAN?Aciss3.popNotify("\u60a8\u8f93\u5165\u7684\u9875\u7801\u8d85\u8fc7\u4e86\u603b\u9875\u6570\uff01"):Aciss3.popNotify("Your input number exceeds the number of total pages."):(this.start=(a-1)*b,this.now_page=parseInt(a),b=this.submit_params,b.start=this.start,b.limit=this.page_size,this._loadGridData("no_init",b)):alert("Please input a number."))},_refreshPage:function(){var a=this.page_size,b=this.submit_params;b.start=this.start;b.limit=
a;this._loadGridData("no_init",b,null)},refreshPage:function(a){var b=this.page_size,c=this.submit_params;c.start=this.start;c.limit=b;this.now_page=this.start/this.page_size+1;this._loadGridData("no_init",c,a)},_setNowPageCount:function(){var a=this.now_page,b=this.Id,c=b+"_bottom_page_input";$("#"+(b+"_top_page_input")).val(a);$("#"+c).val(a)},_setPageCount:function(){var a=this.page_count,b=this.Id,c=b+"_top_paging_bar_total_page",b=b+"_bottom_paging_bar_total_page";"ch"==LAN?($("#"+c).text(" \u5171 "+
a+" \u9875"),$("#"+b).text(" \u5171 "+a+" \u9875")):($("#"+c).text(" Of "+a+" "),$("#"+b).text(" Of "+a+" "))},_setPageTip:function(){var a=this.Id,b=a+"_bottom_page_tip",c=this.start+1,d=this.start+this.page_size,e=this.total_count,f=d;e<d&&(f=e);c="ch"==LAN?"\u7b2c"+c+" \u81f3 "+f+" \u6761\u6570\u636e\uff0c\u5171 "+e+" \u6761\u3002":c+" - "+f+" Of "+e+" Records.";$("#"+(a+"_top_page_tip")).text(c);$("#"+b).text(c)},_genPagingBar:function(a){var b=this.Id,c=$('<div class="row" style="font-size:14px;margin-top:10px;"></div>'),
d=$('<div class="col-xs-12"></div>'),e=$('<div class="table-btn-box"></div>'),f=$('<span class="glyphicon glyphicon-step-backward pointer" aria-hidden="true" style="cursor:pointer;"></span>');e.append(f);var g=$('<span class="glyphicon glyphicon-triangle-left pointer" style="margin-left:5px;" aria-hidden="true" style="cursor:pointer;"></span>');e.append(g);"ch"==LAN?e.append("<span>&nbsp;|&nbsp;</span>\u9875\u6570"):e.append("<span>&nbsp;|&nbsp;</span>Page");var h=$('<input id="'+(b+"_"+a+"_page_input")+
'" type="text" style="margin-left:5px;outline:none;border:none;width:50px;height:26px;border-radius:2px;border:1px #ddd solid;"/>');e.append(h);var m=b+"_"+a+"_paging_bar_total_page",m="ch"==LAN?$('<span id="'+m+'" style="margin-left:3px;"> \u5171 </span>'):$('<span id="'+m+'" style="margin-left:3px;"> Of </span>');e.append(m);e.append("<span>|</span>&nbsp;");m=$('<span class="glyphicon glyphicon-triangle-right pointer" aria-hidden="true" style="cursor:pointer;"></span>');e.append(m);var k=$('<span class="glyphicon glyphicon-step-forward pointer" aria-hidden="true" style="margin-left:5px;" style="cursor:pointer;"></span>');
e.append(k);e.append("&nbsp;<span>|</span>&nbsp;");var n=$('<span class="glyphicon glyphicon-repeat pointer" aria-hidden="true" style="cursor:pointer;"></span>&nbsp;');e.append(n);a=$('<span id="'+(b+"_"+a+"_page_tip")+'" class="pull-right"> </span>');e.append(a);d.append(e);c.append(d);f.on("click",this._firstPage.bind(this));g.on("click",this._prePage.bind(this));m.on("click",this._nextPage.bind(this));k.on("click",this._lastPage.bind(this));n.on("click",this._refreshPage.bind(this));h.on("keypress",
this._jumpPage.bind(this));return c},_initGridData:function(){this.grid_div=$('<div class="dataTables_wrapper form-inline no-footer analog-module">');this.grid_table_div=$('<table role="grid" class="table" border="0" cellpadding="0" cellspacing="0"> ');this._addGridHead();var a=this.submit_params;a.start=this.start;a.limit=this.page_size;this._loadGridData("init",a);this.now_page=1;this.grid_div.append(this.grid_table_div);$("#"+this.main_div).append(this.grid_div)},_addGridHead:function(){if(this.column_list.length!=
this.show_column_list.length)throw Error("From Tuxiong: \u8868\u5934\u7684\u4e2a\u6570\u4e0e\u5217\u6570\u4e0d\u5339\u914d\u3002");if(this.column_list.length!=this.widths.length)throw Error("From Tuxiong: \u5bbd\u5ea6\u7684\u5c5e\u6027\u4e2a\u6570\u4e0e\u5217\u6570\u4e0d\u5339\u914d\u3002");if(this.column_list.length!=this.sorts.length)throw Error("From Tuxiong: \u662f\u5426\u6392\u5e8f\u7684\u5c5e\u6027\u4e2a\u6570\u4e0e\u5217\u6570\u4e0d\u5339\u914d\u3002");if(this.column_list.length!=this.renderers.length)throw Error("From Tuxiong: \u6e32\u67d3\u5217\u6570\u636e\u7684\u5c5e\u6027\u4e2a\u6570\u4e0e\u5217\u6570\u4e0d\u5339\u914d\u3002");
if("yes"==this.editable&&this.column_list.length!=this.editable_list.length)throw Error("From Tuxiong: \u5217\u53ef\u5426\u7f16\u8f91\u5c5e\u6027\u4e2a\u6570\u4e0e\u5217\u6570\u4e0d\u5339\u914d\u3002");for(var a=$("<thead></thead>"),b=$('<tr role="row"></th>'),c=this.show_column_list,d=this.sorts,e=this.widths,f=0;f<c.length;f++){var g=d[f],h=c[f],m=e[f],k=$('<th style="width: '+m+'px;font-size:16px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0">'+h+"</th>");"yes"==g&&(k=$('<th style="width: '+
m+'px;font-size:16px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" class="sorting">'+h+"</th>"));b.append(k)}a.append(b);this.grid_table_div.append(a)},_loadGridData:function(a,b,c){var d=this,e=path+this.post_url;Aciss3.isEmpty(this.id_str)||(b.id_str=this.id_str);$.post(e,b,function(b){if(b.success){var e=b.totalCount;b=b.data;d.data_list=b;d._renderGridData(a,b);d.total_count=e;d.page_count=Math.ceil(d.total_count/d.page_size);d._setPageCount();d._setNowPageCount();d._setPageTip();
$("#"+d.main_div).trigger("afterload");void 0!=c&&null!=c&&c(d)}else"session_out"==b.stauts?(alert("Session out. Please login again!"),Aciss3.openUrl(path+"/module/login/login.jsp")):alert("\u5931\u8d25\uff0c\u8bf7\u7a0d\u5019\u518d\u8bd5\u3002")})},_renderGridData:function(a,b){var c=this.column_list;"init"==a?this.tbody_div=$("<tbody>"):"no_init"==a&&this.tbody_div.empty();var d=this.renderers,e=this.widths,f=this.main_id,g=this.Id,h=this.editable,m=[],k="";if("yes"==h&&(m=this.editable_list,k=
this.edit_event,Aciss3.isEmpty(k)))throw Error("From Tuxiong: Editable Grid\u5fc5\u987b\u6307\u5b9aedit_event, single\u4e3a\u5355\u51fb\uff0cdouble\u4e3a\u53cc\u51fb");this.row_data_dict={};for(var n=0;n<b.length;n++){var l=b[n],p=l[f];this.row_data_dict[p]=l;for(var q=g+"_row_"+p,r=$('<tr id="'+q+'" role="row" class="gradeA odd">'),s=0;s<c.length;s++){var u=d[s],w=c[s],F=e[s],v=l[w],C=q+"_"+s,D="no";"yes"==h&&(D=m[s]);Aciss3.isEmpty(v)&&(v="");var x=$('<td style="text-align:center;" id="'+C+'">');
""!=u&&(v=u(p,v,l,x));x.html(v);var z=this.edit_callback;r.append(x).each(function(){if("yes"==h&&"yes"==D){var a="";"single"==k?a="click":"double"==k&&(a="dblclick");x.on(a,function(a,b,c,d,e,f,h,k){return function(){var c=g+"_row_"+h+k+"_input";$(a).html("<input style='width:"+d+"px' id='"+c+"' class='form-control' value='"+b+"'>");$("#"+c).focus();$("#"+c).select();$("#"+c).on("blur",function(){var b=$("#"+c).val();$(a).html(b);Aciss3.isEmpty(z)||z(h,g,e,b,a,f)});$("#"+c).on("keydown",function(b){13==
b.keyCode&&(b=$("#"+c).val(),$(a).html(b),Aciss3.isEmpty(z)||z(h,g,e,b,a,f))})}}(x,v,C,F,w,q,p,s))}})}this.tbody_div.append(r)}this.grid_table_div.append(this.tbody_div)},_addTopPagingBar:function(){var a=this.paging_pos;"no"==a||"both"!=a&&"top"!=a||(this.topPagingBar=this._genPagingBar("top"),$("#"+this.main_div).append(this.topPagingBar))},_addBottomPagingBar:function(){var a=this.paging_pos;"no"==a||"both"!=a&&"bottom"!=a||(this.bottomPagingBar=this._genPagingBar("bottom"),$("#"+this.main_div).append(this.bottomPagingBar))},
addRow:function(){for(var a=this.column_list,b=[],c=0;c<a.length;c++)b.push("");this._renderGridData("",[b])},getRowDataTotalCount:function(){return this.total_count},getDataList:function(){return this.data_list},getRowTrByRowMainId:function(a){return $("#"+this.Id+"_row_"+a)},getRowDataByRowMainId:function(a){return this.row_data_dict[a]},getSubmitParams:function(){return this.submit_params},setSubmitParams:function(a){this.submit_params=a},colorRowByMainId:function(a,b){var c=$("#"+this.Id+"_row_"+
a);c.css("background-color",b);c.siblings().css("background-color","transport")},removeAllTdEventListener:function(){$(this.tbody_div).find("td").off()},resetGrid:function(){this.start=0;this.now_page=1}};function object(a){function b(){}b.prototype=a;return new b}function inheritPrototype(a,b){var c=object(b.prototype);c.constructor=a;a.prototype=c}Aciss3.baseGridWithCheckbox=function(){Aciss3.baseGrid.apply(this,arguments)};inheritPrototype(Aciss3.baseGridWithCheckbox,Aciss3.baseGrid);
Aciss3.baseGridWithCheckbox.prototype._addGridHead=function(){if(this.column_list.length!=this.show_column_list.length)throw Error("From Tuxiong: \u8868\u5934\u7684\u4e2a\u6570\u4e0e\u5217\u6570\u4e0d\u5339\u914d\u3002");if(this.column_list.length!=this.widths.length)throw Error("From Tuxiong: \u5bbd\u5ea6\u7684\u5c5e\u6027\u4e2a\u6570\u4e0e\u5217\u6570\u4e0d\u5339\u914d\u3002");if(this.column_list.length!=this.sorts.length)throw Error("From Tuxiong: \u662f\u5426\u6392\u5e8f\u7684\u5c5e\u6027\u4e2a\u6570\u4e0e\u5217\u6570\u4e0d\u5339\u914d\u3002");
if(this.column_list.length!=this.renderers.length)throw Error("From Tuxiong: \u6e32\u67d3\u5217\u6570\u636e\u7684\u5c5e\u6027\u4e2a\u6570\u4e0e\u5217\u6570\u4e0d\u5339\u914d\u3002");var a=$('<thead class="table-thead"></thead>'),b=$('<tr role="row"></th>'),c=this.show_column_list,d=this.sorts,e=this.widths,f=$('<th style="width: 30px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0"><input id="'+this.Id+'_check_th" type="checkbox"></th>');b.append(f);for(f=0;f<c.length;f++){var g=d[f],
h=c[f],m=e[f],k=$('<th style="width: '+m+'px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0">'+h+"</th>");"yes"==g&&(k=$('<th style="width: '+m+'px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" class="sorting">'+h+"</th>"));b.append(k)}a.append(b);this.grid_table_div.append(a)};
Aciss3.baseGridWithCheckbox.prototype._initGridData=function(){this.selected_items=[];this.grid_div=$('<div class="dataTables_wrapper form-inline no-footer analog-module">');this.grid_table_div=$('<table role="grid" class="table" border="0" cellpadding="0" cellspacing="0"> ');this._addGridHead();var a=this.submit_params;a.start=this.start;a.limit=this.page_size;this._loadGridData("init",a);this.now_page=1;this.grid_div.append(this.grid_table_div);$("#"+this.main_div).append(this.grid_div);$("#"+this.Id+
"_check_th").iCheck({checkboxClass:"icheckbox_minimal-blue",radioClass:"iradio_minimal-blue",increaseArea:"20%"});$("#"+this.Id+"_check_th").on("ifChecked",this.selectAll.bind(this));$("#"+this.Id+"_check_th").on("ifUnchecked",this.removeAll.bind(this))};
Aciss3.baseGridWithCheckbox.prototype._renderGridData=function(a,b){var c=this.column_list;"init"==a?this.tbody_div=$("<tbody>"):"no_init"==a&&this.tbody_div.empty();$("#"+this.Id+"_check_th").iCheck("uncheck");var d=this.renderers,e=this.main_id;this.row_data_dict={};for(var f=0;f<b.length;f++){var g=b[f],h=g[e];this.row_data_dict[h]=g;var m=$('<tr id="'+this.Id+"_row_"+h+'" role="row" class="gradeA odd">'),k="";0<=$.inArray(""+h,this.selected_items)&&(k="checked");k=$('<td class="basegrid_checkbox"><input id="'+
this.Id+"_"+h+'_check_td" type="checkbox" value="'+h+'" '+k+"></td>");m.append(k);for(k=0;k<c.length;k++){var n=d[k],l=g[c[k]];Aciss3.isEmpty(l)&&(l="");var p=$("<td>");""!=n&&(l=n(h,l,g,p));p.html(l);m.append(p)}this.tbody_div.append(m)}this.grid_table_div.append(this.tbody_div);this.grid_div.find("input:not(#"+this.Id+"_check_th)").iCheck({checkboxClass:"icheckbox_minimal-blue",radioClass:"iradio_minimal-blue",increaseArea:"20%"});var q=this;this.grid_div.find("input:not(#"+this.Id+"_check_th)").each(function(){$(this).on("ifChecked",
q.addSelectedItem.bind(q,$(this).val()));$(this).on("ifUnchecked",q.removeSelectedItem.bind(q,$(this).val()))})};Aciss3.baseGridWithCheckbox.prototype.selectAll=function(){$("#"+this.Id+"_check_th").iCheck("check");this.grid_div.find("input:not(#"+this.Id+"_check_th)").iCheck("check")};Aciss3.baseGridWithCheckbox.prototype.removeAll=function(){$("#"+this.Id+"_check_th").iCheck("uncheck");this.grid_div.find("input:not(#"+this.Id+"_check_th)").iCheck("uncheck")};
Aciss3.baseGridWithCheckbox.prototype.addSelectedItem=function(a){0>$.inArray(a,this.selected_items)&&this.selected_items.push(a)};Aciss3.baseGridWithCheckbox.prototype.removeSelectedItem=function(a){a=$.inArray(a,this.selected_items);0<=a&&this.selected_items.splice(a,1)};Aciss3.baseCheckBox=function(){this.init.apply(this,arguments)};
Aciss3.baseCheckBox.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.initCheckbox();Aciss3[this.Id]=this},initCheckbox:function(){var a=$("#"+this.main_div),b=this.value_label,c=this.Id;a.append('<input style="display:none;" id="'+(c+"_hidden")+'">');var d=$('<input id="'+c+'" type="checkbox" name="" value="0">');d.on("ifChecked",function(){$("#"+c+"_hidden").val(1)});d.on("ifUnchecked",function(){$("#"+c+"_hidden").val(0)});d.iCheck("check");a.append(d);a.append("&nbsp;"+
b);$("#"+c).iCheck({checkboxClass:"icheckbox_minimal-blue",radioClass:"iradio_minimal-blue",increaseArea:"20%"})},getValue:function(){return $("#"+this.Id+"_hidden").val()},check:function(){var a=$("#"+this.Id);$("#"+this.Id+"_hidden").val(1);a.iCheck("check")},uncheck:function(){var a=$("#"+this.Id);$("#"+this.Id+"_hidden").val(0);a.iCheck("uncheck")},disable:function(){var a=$("#"+this.Id);$("#"+this.Id+"_hidden").val(0);a.iCheck("uncheck");a.attr("disabled","disabled")},enable:function(){$("#"+
this.Id).removeAttr("disabled")}};Aciss3.exportCheckBoxField=function(){this.init.apply(this,arguments)};
Aciss3.exportCheckBoxField.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.initCheckBoxField();Aciss3[this.Id]=this},initCheckBoxField:function(){var a=this.Id,b=this.field_value,b=this.field_value,c=$("#"+this.main_div),d="checkbox_"+a,e="field_"+a,f="checkbox_"+a+"_hidden",g=$('<div style="margin-top:5px;" class="col-xs-3">'),h=$("<span>&nbsp;"+b+"</span>"),m=$('<input style="display:none;" id="'+f+'">'),d=$('<input id="'+d+'" type="checkbox" name="" value="0">');g.append(m);
g.append(d);g.append(h);c.append(g);d.on("ifChecked",function(){$("#"+f).val(1)});d.on("ifUnchecked",function(){$("#"+f).val(0)});d.iCheck("check");$("#checkbox_"+a).iCheck({checkboxClass:"icheckbox_minimal-blue",radioClass:"iradio_minimal-blue",increaseArea:"20%"});g=$('<div style="margin-top:5px;" class="col-xs-3">');h="";h=$('<input class="form-control" type="text" id="'+e+'" value="'+b+'">');g.append(h);c.append(g);$("#checkbox_"+a).on("ifChecked",function(a){$("#"+e).attr("disabled",!1);$("#"+
f).val(1)});$("#checkbox_"+a).on("ifUnchecked",function(a){$("#"+e).attr("disabled",!0);$("#"+f).val(0)})},getValue:function(){var a=this.Id,b="field_"+a;return 1==$("#"+("checkbox_"+a+"_hidden")).val()?$("#"+b).val():""},setValue:function(a){var b=this.Id,c="field_"+b;$("#checkbox_"+b).iCheck("check");$("#"+c).val(a)},empty:function(){var a=this.Id;$("#checkbox_"+a).iCheck("uncheck");$("#field_"+a).val("")},check:function(){$("#checkbox_"+this.Id).iCheck("check")},uncheck:function(){$("#checkbox_"+
this.Id).iCheck("uncheck")}};Aciss3.baseCheckBoxField=function(){this.init.apply(this,arguments)};
Aciss3.baseCheckBoxField.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.initCheckBoxField();Aciss3[this.Id]=this},initCheckBoxField:function(){var a=this.enable,b=this.Id,c=this.checkbox_value_label,d=this.field_value,d=this.field_value,e=$("#"+this.main_div),f="checkbox_"+b,g="field_"+b,h="checkbox_"+b+"_hidden",m=$('<div style="margin-top:5px;" class="col-xs-2">'),k=$('<input style="display:none;" id="'+h+'">'),f=$('<input id="'+f+'" type="checkbox" name="" value="0">');
m.append(k);a||m.append(f);m.append("&nbsp;"+c);e.append(m);f.on("ifChecked",function(){$("#"+h).val(1)});f.on("ifUnchecked",function(){$("#"+h).val(0)});$("#checkbox_"+b).iCheck({checkboxClass:"icheckbox_minimal-blue",radioClass:"iradio_minimal-blue",increaseArea:"20%"});c=$('<div style="margin-top:5px;" class="col-xs-4">');m="";a?(m=$('<input class="form-control" type="text" id="'+g+'" value="'+d+'">'),$("#"+h).val(1)):m=$('<input disabled="true" class="form-control" type="text" id="'+g+'" value="'+
d+'">');c.append(m);e.append(c);$("#checkbox_"+b).on("ifChecked",function(a){$("#"+g).attr("disabled",!1);$("#"+h).val(1)});$("#checkbox_"+b).on("ifUnchecked",function(a){$("#"+g).attr("disabled",!0);$("#"+h).val(0)})},getValue:function(){var a=this.Id,b="field_"+a;return 1==$("#"+("checkbox_"+a+"_hidden")).val()?$("#"+b).val():""},setValue:function(a){var b=this.Id,c="field_"+b;$("#checkbox_"+b).iCheck("check");$("#"+c).val(a)},empty:function(){var a=this.Id;$("#checkbox_"+a).iCheck("uncheck");$("#field_"+
a).val("")},check:function(){$("#checkbox_"+this.Id).iCheck("check")},uncheck:function(){$("#checkbox_"+this.Id).iCheck("uncheck")}};Aciss3.staticCombo=function(){this.init.apply(this,arguments)};
Aciss3.staticCombo.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.initComboData();Aciss3[this.Id]=this},initComboData:function(){var a=this.req_type;Aciss3.isEmpty(a)&&(a="no");this.combo_div=$("<div>");this.combo_select_div=$('<select reqType="'+a+'" class="form-control" id="'+this.Id+'">');this.renderCombo(this.data_list);this.combo_div.append(this.combo_select_div);$("#"+this.main_div).append(this.combo_div)},renderCombo:function(a){this.combo_select_div.empty();this.combo_select_div.append('<option value="" selected="true" disabled="true" style="display:none;"></option>');
for(var b=0;b<a.length;b++){var c=a[b];this.combo_select_div.append('<option value="'+c[0]+'" >'+c[1]+"</option> ")}},reset:function(){this.combo_select_div.val("")},getValue:function(){return $("#"+this.Id).val()},setValue:function(a){$("#"+this.Id).val(a)}};Aciss3.selectedCombo=function(){Aciss3.staticCombo.apply(this,arguments)};inheritPrototype(Aciss3.selectedCombo,Aciss3.staticCombo);
Aciss3.selectedCombo.prototype.renderCombo=function(a){var b=this.selected_callback,c=this.init_value;this.combo_select_div.empty();this.combo_select_div.append('<option value="" selected="true" disabled="true" style="display:none;"></option>');for(var d=0;d<a.length;d++){var e=a[d],f=e[0],e=e[1];f==c?this.combo_select_div.append('<option value="'+f+'" selected="true">'+e+"</option> "):this.combo_select_div.append('<option value="'+f+'" >'+e+"</option> ")}$(this.combo_select_div).change(function(){var a=
$(this).find("option:selected").text();Aciss3.isEmpty(b)||b(a)})};Aciss3.baseCombo=function(){this.init.apply(this,arguments)};
Aciss3.baseCombo.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.initComboData()},initComboData:function(){this.combo_div=$('<div class="form-group">');this.combo_select_div=$('<select class="form-control" id="'+this.Id+'">');void 0!=this.data?this.renderCombo(this.data):this.loadComboData(this.submitParams);this.combo_div.append(this.combo_select_div);$("#"+this.main_div).append(this.combo_div)},loadComboData:function(a){var b=this;$.post(path+this.post_url,a,function(a){a.success?
b.renderCombo(a.data):alert("\u5931\u8d25\uff0c\u8bf7\u7a0d\u5019\u518d\u8bd5\u3002")})},renderCombo:function(a){var b=this,c=this.display_field,d=this.value_field;this.combo_select_div.empty();this.combo_select_div.append('<option value="" selected="true" disabled="true" style="display:none;"></option>');for(var e=0;e<a.length;e++){var f=a[e],f=$('<option value="'+f[d]+'" >'+f[c]+"</option> ");this.combo_select_div.append(f);f.on("click",function(){$("#"+b.id).trigger("change")})}}};
Aciss3.matchCombo=function(){this.init.apply(this,arguments)};
Aciss3.matchCombo.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.initMatchCombo();Aciss3[this.Id]=this},initMatchCombo:function(){var a=this.req_type;Aciss3.isEmpty(a)&&(a="no");this.combo_input=$('<input reqType="'+a+'" id="'+this.Id+'_input" type="text" class="form-control" placeholder="'+this.place_holder+'">');this.combo_input.on("focus",this.matchComboFocusAction.bind(this));this.combo_input.on("keyup",this.matchComboKeyUpAction.bind(this));this.combo_input.on("blur",
this.matchComboBlurAction.bind(this));this.combo_list=$('<div id="'+this.Id+'_combo" class="namepropertycollapse">');this.combo_ul=$('<ul id="'+this.Id+'_ul">');this.combo_list.append(this.combo_ul);this.combo_input_true_value=$('<input id="'+this.Id+'_input_hidden" type="text" style="display:none;">');a=$("#"+this.main_div);a.append(this.combo_input);a.append(this.combo_list);a.append(this.combo_input_true_value)},matchComboFocusAction:function(){this.loadComboData()},matchComboKeyUpAction:function(){this.loadComboData()},
loadComboData:function(){var a=this.submit_params,b=this.combo_input.val();a.search_word=b;b=this.parent_combo_attr;if(!Aciss3.isEmpty(b))for(var c=b.split(";"),d=this.parent_combo_div.split(";"),b=0;b<c.length;b++){var e=c[b];if(!Aciss3.isEmpty(e)){var f=d[b],f=Aciss3.isEmpty(Aciss3.getCmp(f))?$("#"+f).val():Aciss3.getCmp(f).getValue();a[e]=f}}c=this.child_combo_div;if(!Aciss3.isEmpty(c))if("object"==typeof c)for(b=0;b<c.length;b++)Aciss3.getCmp(c[b]).clear();else Aciss3.getCmp(c).clear();var g=
this;$.post(path+this.post_url,a,function(a){if(a.success){a=a.data;var b=g.combo_ul;b.empty();if(!Aciss3.isEmpty(a))for(var c=0;c<a.length;c++){var d=a[c],e=d[0],d=d[1],f=$("<li>");f.html(d);f.on("click",function(a,b){return function(){g.selectComboItem(a,b)}}(e,d));b.append(f)}g.combo_list.show()}})},matchComboBlurAction:function(a){var b=this,c=this.allow_fill;Aciss3.getCmp(c)&&(c=!1);var d=setTimeout(function(){if(!c){for(var a=[],f=b.combo_ul.children("li"),g=0;g<f.length;g++){var h=$(f[g]);
a.push(h.text())}f=b.getShowValue();-1==a.indexOf(f)&&b.reset()}b.combo_list.hide();clearTimeout(d)},200)},selectComboItem:function(a,b){this.combo_input.val(b);this.combo_input_true_value.val(a);this.combo_input_true_value.trigger("change");$("#"+this.main_div).trigger("selected")},getComboUl:function(){return this.combo_ul},getShowValue:function(){return this.combo_input.val()},getValue:function(){return this.combo_input_true_value.val()},setShowValue:function(a){this.combo_input.val(a)},setValue:function(a){this.combo_input_true_value.val(a)},
reset:function(){this.combo_input.val("");this.combo_input_true_value.val("")},reload:function(){this.combo_ul.empty();this.loadComboData()},clear:function(){this.combo_input.val("");this.combo_ul.empty()},disable:function(){this.reset();this.combo_input.attr("disabled",!0)},disableWithoutReset:function(){this.combo_input.attr("disabled",!0)},enable:function(){this.combo_input.attr("disabled",!1)},selectFirstData:function(){var a=this.submit_params,b=this.combo_input.val();a.search_word=b;b=this.parent_combo_attr;
if(!Aciss3.isEmpty(b))for(var c=b.split(";"),d=this.parent_combo_div.split(";"),b=0;b<c.length;b++){var e=c[b];if(!Aciss3.isEmpty(e)){var f=d[b],f=Aciss3.isEmpty(Aciss3.getCmp(f))?$("#"+f).val():Aciss3.getCmp(f).getValue();a[e]=f}}c=this.child_combo_div;if(!Aciss3.isEmpty(c))if("object"==typeof c)for(b=0;b<c.length;b++)Aciss3.getCmp(c[b]).clear();else Aciss3.getCmp(c).clear();var g=this;$.post(path+this.post_url,a,function(a){if(a.success){a=a.data;var b=g.combo_ul;b.empty();for(var c=0;c<a.length;c++){var d=
a[c],e=d[0],d=d[1],f=$("<li>");f.html(d);f.on("click",function(a,b){return function(){g.selectComboItem(a,b)}}(e,d));b.append(f)}0<a.length&&(a=a[0],g.selectComboItem(a[0],a[1]))}})}};Aciss3.dateInput=function(){this.init.apply(this,arguments)};
Aciss3.dateInput.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.initDateInput();Aciss3[this.Id]=this},initDateInput:function(){var a=$("#"+this.main_div),b="no";null!=this.req_type&&"yes"==this.req_type&&(b="yes");var c=$('<div class="input-group date form_date" data-date="" data-date-format="yyyy-mm-dd" data-link-format="mm/dd/yyyy">'),b=$('<input class="form-control" type="text" value="" reqType="'+b+'" style="background-color:#fff;" id="'+this.Id+'">'),d=$('<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>');
c.append(b);c.append(d);a.append(c);formatDatePlugin();this.date_input=b},getValue:function(){return this.date_input.val()}};Aciss3.TabPanel=function(){this.init.apply(this,arguments)};
Aciss3.TabPanel.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.tab_list=[];this.initTabPanel();Aciss3[this.Id]=this;return this},initTabPanel:function(){var a=$("#"+this.main_div),b=$('<ul id="'+this.Id+'_tab" class="nav nav-tabs"></ul>');this.tab_ul=b;var c=$('<div class="tab-content" id="'+this.Id+'"></div>');this.tab_content=c;a.append(b);a.append(c);var d=this;b.on("click",function(a){a=a.target;$(a).hasClass("close-tab")&&d._closeTab(a)})},_closeTab:function(a){a=a.parentNode;
var b=a.id.replace("_nav",""),c=$("#"+a.id).closest("li");c.hasClass("active")?(c.prev().children("a").eq(0).tab("show"),c.prev().children("a").eq(0).one("shown.bs.tab",function(a){c.remove();$("#"+b).remove()})):(c.remove(),$("#"+b).remove())},addTab:function(a){var b=a.title,c=a.shown,d=a.closable,e=this.tab_ul,f=this.tab_content;a=this.Id+a.id;var g=a+"_nav";if(0<$("#"+g).length)$("#"+g).children("a").eq(0).tab("show");else{var h=$('<div id="'+a+'" class="tab-pane fade"></div>'),b=$('<a id="a_'+
a+'" href="#'+a+'" data-toggle="tab" style="font-weight:bold;">'+b+"</a>"),g=$('<li id="'+g+'">');!0==d&&(d=$('<i class="close-tab glyphicon glyphicon-remove"></i>'),g.append(d));g.append(b);e.append(g);f.append(h);!0==c&&b.tab("show");b.on("click",function(a){a.preventDefault();$(this).tab("show")})}return a},refreshTab:function(a,b){var c=this.Id+a;$("#"+c).empty();"str"==typeof b?$("#"+c).html(b):"object"==typeof b&&$("#"+c).append(b)},closeTab:function(a){var b=this.Id+a,c=$("#"+(b+"_nav")).closest("li");
c.hasClass("active")?(c.prev().children("a").eq(0).on("shown.bs.tab",function(a){c.remove();$("#"+b).remove()}),c.prev().children("a").eq(0).tab("show")):(c.remove(),$("#"+b).remove())},showTab:function(a){a=this.Id+a;0<$("#"+a).length&&$("#"+(a+"_nav")).closest("li").children("a").eq(0).tab("show")},getTabId:function(a){a=this.Id+a;return 0<$("#"+a).length?a:null},closeAllTab:function(){var a=this.Id,b=$("#"+(this.Id+"_tab")),a=$("#"+a);b.empty();a.empty()},destoryTabs:function(){$("#"+this.Id+"_tab").remove();
$("#"+this.Id).remove()}};Aciss3.NoteTabPanel=function(){Aciss3.TabPanel.apply(this,arguments)};inheritPrototype(Aciss3.NoteTabPanel,Aciss3.TabPanel);Aciss3.NoteTabPanel.prototype.setTabNote=function(a,b){$("#note_"+a).html(b);this.refreshTabTitle(a,b)};Aciss3.NoteTabPanel.prototype.refreshTabTitle=function(a,b){var c=$("#"+a+"_nav");"0"==b?c.addClass("li-disabled"):c.removeClass("li-disabled")};
Aciss3.NoteTabPanel.prototype.addNewTab=function(a){var b=this.addTab(a);a=a.note;var c=$("#a_"+b);Aciss3.isEmpty(a)||(tab_note_span=$('<span>(</span><span id="note_'+b+'">'+a+"</span><span>)</span>"),c.append(tab_note_span));this.refreshTabTitle(b,a);return b};Aciss3.ExcelTable=function(){this.init.apply(this,arguments)};
Aciss3.ExcelTable.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.tab_list=[];this.initExcelTable();Aciss3[this.Id]=this;return this},initExcelTable:function(){var a=this,b=$('<table id="'+this.Id+'" class="table table-bordered">'),c=$("<tr>");c.append(this.th);b.append(c);for(var c=this.init_row_count,d=this.init_column_count,e=this._dblClickAction,f=0;f<c;f++){for(var g=$("<tr>"),h=0;h<d;h++){var m=$('<td style="cursor:text">&nbsp;</td>');g.append(m);m.on("dblclick",function(b){return function(){e(b,
a)}}(m))}b.append(g)}$("#"+this.main_div_id).append(b);this.table=b},_dblClickAction:function(a,b){var c=a.html();0!=a.has("textarea").length&&(c=a.find(">:first-child").val());a.empty();var d=$('<textarea style="height:30px;" class="form-control">');"&nbsp;"!=c&&d.val(c);a.append(d);d.on("blur",function(){var c=d.val();a.empty();a.html(c);c=b.change_action;void 0!=c&&c()});a.on("keypress",function(c){13==c.which&&(c=d.val(),a.empty(),a.html(c),c=b.change_action,void 0!=c&&c())});var e=b._fillPasteDataAction;
a.on("paste",function(a){setTimeout(function(){e(d,b)},100)})},_fillPasteDataAction:function(a,b){var c=b.table,d=b._dblClickAction;c.find("tr:gt(0)").remove();for(var e=a.val(),e=$.trim(e).split("\n"),f=0;f<e.length;f++){for(var g=$("<tr>"),h=e[f].split("\t"),m=0;m<h.length;m++){var k=$("<td>"+h[m]+"</td>");k.on("dblclick",function(a){return function(){d(a,b)}}(k));g.append(k)}c.append(g)}c=b.change_action;void 0!=c&&c()},getData:function(){for(var a=[],b=this.table.find("tr"),c=1;c<b.length;c++){for(var d=
$(b[c]).find("td"),e=[],f=0;f<d.length;f++){var g=$(d[f]).html();e.push(g)}a.push(e)}return a},getDataStr:function(){for(var a=this.getData(),b="",c=0;c<a.length;c++)var d=a[c].join(","),b=b+(d+";");return b},setData:function(a){var b=this.table,c=this._dblClickAction;b.find("tr:gt(0)").remove();for(var d=0;d<a.length;d++){for(var e=$("<tr>"),f=a[d],g=0;g<f.length;g++){var h=$("<td>"+f[g]+"</td>");h.on("dblclick",function(a,b){return function(){c(a,b)}}(h));e.append(h)}b.append(e)}},setDataStr:function(a){a=
a.replace(/(^;)|(;$)/g,"");var b=[],c=[],b=a.split(";");for(a=0;a<b.length;a++)c[a]=b[a].split(",");this.setData(c)},reset:function(){for(var a=this.table.find("tr"),b=1;b<a.length;b++)for(var c=$(a[b]).find("td"),d=0;d<c.length;d++)$(c[d]).html("&nbsp;")}};Aciss3.TimelineItme=function(){this.init.apply(this,arguments)};
Aciss3.TimelineItme.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;Aciss3[this.Id]=this;this.initTimelineItem();return this},initTimelineItem:function(){},genTimeItemDiv:function(){var a=this.item_related_id,b=this.tab_module,c=this.item_module_show,d=this.item_module,e=new Date,f=this.item_date.replace(/-/g,"/"),g=new Date(Date.parse(f)),f=$('<div class="timeline-item active">'),h=$('<div class="year">'+this.item_date+"</div>");h.append('<span class="marker"><span class="dot"></span></span>');
var m=$('<div class="info">');g>e&&(m=$('<div class="info" style="border-left: 4px dotted #D6DFE7">'));m.append('<span style="font-weight:bold;font-size:16px;">'+this.item_step+"&nbsp;&nbsp;-&nbsp;&nbsp;"+c+"</span>");c=$("<table>");"fbdd"!=d&&(e="Target","ch"==LAN&&(e="\u9776\u6807"),void 0!=this.item_target?c.append("<tr><td>"+e+':&nbsp;&nbsp;</td><td><a class="detail_info_a_link" onclick="showTargetDetailById(\''+this.item_target_id+"','"+this.item_target+"','"+b+"')\">"+this.item_target+"</a></td></tr>"):
c.append("<tr><td>"+e+":&nbsp;&nbsp;</td><td>No info.</td></tr>"));e="Creator";g="Step Comments";"ch"==LAN&&(e="\u521b\u5efa\u7528\u6237",g="\u5f53\u524d\u6b65\u9aa4\u5907\u6ce8");c.append("<tr><td>"+e+":&nbsp;&nbsp;</td><td>"+this.item_user+"</td></tr>");c.append("<tr><td>"+g+":&nbsp;&nbsp;</td><td>"+this.item_step_comments+"</td></tr>");for(e=0;e<this.data_name_list.length;e++)c.append("<tr><td>"+this.data_name_list[e]+"</td><td>"+this.data_value_list[e]+"</td></tr>");e="Info";"gene_cloning"==d?
(e="Gene cloning detail info.","ch"==LAN&&(e="Gene cloning\u7684\u8be6\u7ec6\u4fe1\u606f"),c.append("<tr><td>Gene Cloning:&nbsp;&nbsp;</td><td><a onclick=\"showGeneCloningDetailById('"+a+"','"+e+"','"+b+'\')" class="detail_info_a_link">Show detail</a></td>')):"protein_reagent"==d?(e="Protein reagent detail info.","ch"==LAN&&(e="\u86cb\u767d\u8868\u8fbe\u7684\u8be6\u7ec6\u4fe1\u606f"),c.append("<tr><td>Protein reagent :&nbsp;&nbsp;</td><td><a onclick=\"showProteinReagentDetailById('"+a+"','"+e+"','"+
b+"','pro')\" class=\"detail_info_a_link\">Show detail</a></td>")):"protein_reagent_pur"==d?(e="Protein reagent (Purfication) detail info.","ch"==LAN&&(e="\u86cb\u767d\u7eaf\u5316\u7684\u8be6\u7ec6\u4fe1\u606f"),c.append("<tr><td>Protein reagent (Purification):&nbsp;&nbsp;</td><td><a onclick=\"showProteinReagentDetailById('"+a+"','"+e+"','"+b+"','pur')\" class=\"detail_info_a_link\">Show detail</a></td>")):"assay"==d?(e="Assay detail info.","ch"==LAN&&(e="Assay\u8be6\u7ec6\u4fe1\u606f"),c.append("<tr><td>Assay:&nbsp;&nbsp;</td><td><a onclick=\"showAssayDetailById('"+
a+"','"+e+"','"+b+'\')" class="detail_info_a_link">Show detail</a></td>')):"fbdd"==d?(e="FBDD detail info.","ch"==LAN&&(e="FBDD\u7684\u8be6\u7ec6\u4fe1\u606f"),c.append("<tr><td>FBDD:&nbsp;&nbsp;</td><td><a onclick=\"showFbddDetailById('"+a+"','"+e+"','"+b+'\')" class="detail_info_a_link">Show detail</a></td>')):"stru_mounting"==d?(e="Structure (X-tal Mounting) detail info.","ch"==LAN&&(e="\u6676\u4f53\u7ed3\u6784\uff08\u70b9\u6676\uff09\u7684\u8be6\u7ec6\u4fe1\u606f"),c.append("<tr><td>X-tal Mounting:&nbsp;&nbsp;</td><td><a onclick=\"showStruMountingDetailById('"+
a+"','"+e+"','"+b+'\')" class="detail_info_a_link">Show detail</a></td>')):"stru_data"==d?(e="Structure (Data collection) detail info.","ch"==LAN&&(e="\u6676\u4f53\u7ed3\u6784\uff08\u6570\u636e\u6536\u96c6\uff09\u7684\u8be6\u7ec6\u4fe1\u606f"),c.append("<tr><td>Data collection:&nbsp;&nbsp;</td><td><a onclick=\"showStruDataDetailById('"+a+"','"+e+"','"+b+'\')" class="detail_info_a_link">Show detail</a></td>')):"stru_deter"==d&&(e="Structure (Determination) detail","ch"==LAN&&(e="\u6676\u4f53\u7ed3\u6784\uff08\u7ed3\u6784\u786e\u5b9a\uff09\u7684\u8be6\u7ec6\u4fe1\u606f"),
c.append("<tr><td>Determination:&nbsp;&nbsp;</td><td><a onclick=\"showStruDeterDetailById('"+a+"','"+e+"','"+b+'\')" class="detail_info_a_link">Show detail</a></td>'));m.append(c);f.append(h);f.append(m);return f}};Aciss3.ColumnModeExcelTable=function(){this.init.apply(this,arguments)};
Aciss3.ColumnModeExcelTable.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.tab_list=[];this.initColumnModeExcelTable();Aciss3[this.Id]=this;return this},initColumnModeExcelTable:function(){for(var a=this,b=$('<table id="'+this.Id+'" class="table table-bordered">'),c=this.init_row_count,d=this.init_column_count,e=this.th_list,f=this._dblClickAction,a=this,g=0;g<c;g++){for(var h=$("<tr>"),m=0;m<d;m++){var k=$("<td>&nbsp;</td>");if(0==m)k=$('<td width=150 style="background-color:#f7f7f9;"><b>'+
e[g]+"</b></td>");else k.on("dblclick",function(a,b){return function(){f(a,b)}}(k,a));h.append(k)}b.append(h)}$("#"+this.main_div_id).append(b);this.table=b},_dblClickAction:function(a,b){var c=a.html();0!=a.has("textarea").length&&(c=a.find(">:first-child").val());a.empty();var d=$('<textarea style="height:30px;" class="form-control">');"&nbsp;"!=c&&d.val(c);a.append(d);d.on("blur",function(){var c=d.val();a.empty();a.html(c);c=b.change_action;void 0!=c&&c()});a.on("keypress",function(c){13==c.which&&
(c=d.val(),a.empty(),a.html(c),c=b.change_action,void 0!=c&&c())});var e=b._fillPasteDataAction;a.on("paste",function(a){setTimeout(function(){e(d,b)},100)})},_fillPasteDataAction:function(a,b){var c=b._dblClickAction;$("#"+b.Id+" td:not(:first-child)").remove();for(var d=a.val(),d=$.trim(d).split("\n"),e=0;e<d.length;e++)for(var f=$("#"+b.Id+" tr").eq(e),g=d[e].split("\t"),h=0;h<g.length;h++){var m=$("<td>"+g[h]+"</td>");f.append(m);m.on("dblclick",function(a,b){return function(){c(a,b)}}(m,b))}d=
b.change_action;void 0!=d&&d()},getData:function(){for(var a=[],b=this.table.find("tr"),c=0;c<b.length;c++){for(var d=$(b[c]).find("td"),e=[],f=1;f<d.length;f++){var g=$(d[f]).html();e.push(g)}a.push(e)}return a},getDataStr:function(){for(var a=this.getData(),b="",c=0;c<a.length;c++)var d=a[c].join(","),b=b+(d+";");return b},setData:function(a){for(var b=this._dblClickAction,c=this.table.find("tr"),d=0;d<a.length;d++)for(var e=a[d],f=$(c[d]).find("td"),g=1;g<e.length;g++){var h=f[g];$(h).html(e[g]);
$(h).on("dblclick",function(a,c){return function(){b(a,c)}}(h))}},setDataStr:function(a){a=a.replace(/(^;)|(;$)/g,"");var b=[],c=[],b=a.split(";");for(a=0;a<b.length;a++)c[a]=b[a].split(",");this.setData(c)},reset:function(){for(var a=this.table.find("tr"),b=0;b<a.length;b++)for(var c=$(a[b]).find("td"),d=1;d<c.length;d++)$(c[d]).html("&nbsp;")}};Aciss3.genSpaceStr=function(a){for(var b="",c=0;c<a;c++)b+=" ";return b};Aciss3.SeqShowTab=function(){this.init.apply(this,arguments)};
Aciss3.SeqShowTab.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.initSeqShowTab();Aciss3[this.Id]=this;return this},initSeqShowTab:function(){var a=this,b=a.main_div_id,c=a.highlightSearchText,d=a.clearHighlight,e=a.seq,f=$('<div style="margin-top:20px;position:relative;"></div>'),g=$('<pre style="font-size:14px;position:relative;height:505px;"></pre>');this.seq_pre=g;f.append(g);var g=$("<form>"),h=$('<div class="row" style="margin-top:10px;">'),m=$("<span>");this.edit_button_div=
m;g.append(h);var k=$('<div class="col-xs-6 font-gray"></div>'),n=$('<input class="form-control" type="text">');a.search_input=n;k.append(n);h.append(k);n="Search & Highlight";k="Clear";"ch"==LAN&&(n="\u68c0\u7d22\u5e76\u9ad8\u4eae\u663e\u793a",k="\u6e05\u9664");n=$('<button class="btn btn-primary" type="button">'+n+"</button>");n.on("click",c.bind(a));c=$('<button class="btn btn-primary" type="button" style="margin-left:10px;">'+k+"</button>");c.on("click",d.bind(a));h.append(n);h.append(c);h.append(m);
a.showSeq(e);g.on("keypress",function(b){"13"==b.keyCode&&(b.preventDefault(),this.highlightSearchText(a))}.bind(a));$("#"+b).append(g);$("#"+b).append(f)},showSeq:function(a){var b=this.gene_cloning_register_user_id,c=this.addSeq,d=this.editSeq,e=this.deleteSeq;$(this.seq_pre).empty();$(this.edit_button_div).empty();var f="Add Seq.",g="Edit Seq.",h="Delete Seq.";"ch"==LAN&&(f="\u65b0\u589e\u5e8f\u5217",g="\u7f16\u8f91\u5e8f\u5217",h="\u5220\u9664\u5e8f\u5217");f=$('<button class="btn btn-primary" type="button" style="margin-left:185px;"><span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;'+
f+"</button>");f.on("click",c.bind(this));c=$('<button class="btn btn-primary" type="button" style="margin-left:71px;"><span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;'+g+"</button>");c.on("click",d.bind(this));d=$('<button class="btn btn-primary" type="button" style="margin-left:10px;"><span class="glyphicon glyphicon-trash"></span>&nbsp;&nbsp;'+h+"</button>");d.on("click",e.bind(this));if(Aciss3.isEmpty(a))this.seq_pre.append("<span style='margin-top:10px;'>\u6682\u65f6\u6ca1\u6709\u5e8f\u5217\u4fe1\u606f.</span>"),
1==PRI&&USERID==b?this.edit_button_div.append(f):2!=PRI&&3!=PRI&&0!=PRI||this.edit_button_div.append(f);else{1==PRI&&USERID==b&&this.edit_button_div.append(c);if(0==PRI||2==PRI||3==PRI)this.edit_button_div.append(c),this.edit_button_div.append(d);a=a.match(/.{1,5}/g);b=1;e='<div class="seq_content_line">\n\n';d='<div class="seq_index_line">';for(f=h=0;f<a.length;f++)e+=a[f],e+=" ",d+=b.toString(),c=Aciss3.genSpaceStr(6-b.toString().length),d+=c,b+=5,h+=1,0==h%19&&(d+="\n\n\n\n",e+="\n\n\n\n");e+=
"</div>";this.seq_pre.append(d+"</div>");this.seq_pre.append(e)}},highlightSearchText:function(){var a=$(".seq_content_line"),b=$(this.search_input).val().trim();if(Aciss3.isEmpty(b))a="Please fill search text!","ch"==LAN&&(a="\u8bf7\u586b\u5199\u68c0\u7d22\u5185\u5bb9\uff01"),Aciss3.popNotify(a,"danger");else{for(var c="",d=0;d<b.length;d++)c+=b[d]+"\\s*";b=RegExp(c,"gim");a.highlightRegex();a.highlightRegex(b,{tagType:"span",className:"highlight"})}},clearHighlight:function(){$(".seq_content_line").highlightRegex()},
resetSeqEditWin:function(){$("#edit_hidden_flag").val("");$("#edit_hidden_seq_type").val("");$("#edit_hidden_seq_id").val("");$("#edit_hidden_gene_cloning_id").val("");$("#edit_seq_content_textarea").val("")},addSeq:function(){this.resetSeqEditWin();var a=this.seq_id,b=this.seq_type,c=this.gene_cloning_id;$("#edit_hidden_seq_type").val(b);$("#edit_hidden_flag").val("create");$("#edit_hidden_seq_id").val(a);$("#edit_hidden_gene_cloning_id").val(c);$("#edit_gene_cloning_seq_modal").modal()},editSeq:function(){this.resetSeqEditWin();
var a=this.raw_seq,b=this.seq_id;$("#edit_hidden_flag").val("edit");$("#edit_seq_content_textarea").val(a);$("#edit_hidden_seq_id").val(b);$("#edit_gene_cloning_seq_modal").modal()},deleteSeq:function(){var a=this,b="Delete it?";"ch"==LAN&&(b="\u786e\u8ba4\u5220\u9664\uff1f");$.prompt("<span style='font-size:14px;'>"+b+"</span>",{title:"",buttons:{Yes:!0,No:!1},submit:function(b,d,e,f){d&&(b={},b.gene_cloning_seq_id=a.seq_id,d=path+"/DeleteGeneCloningSeq",$.bootstrapLoading.start({loadingTips:Aciss3.loadingStr}),
$.post(d,b,function(b){b=b.success;$.bootstrapLoading.end();b&&(Aciss3.popSuccessNotify(),a.showSeq(""))}))}})}};
var loadSideToolBar=function(){var a="Message";"ch"==LAN&&(a="\u7cfb\u7edf\u6d88\u606f");var b=["Inbox","Sent Items"];"ch"==LAN&&(b=["\u6536\u4ef6\u7bb1","\u5df2\u53d1\u9001"]);(new Aciss3.sideToolbarMenu(a,b,["/module/message/inbox.jsp","/module/message/outbox.jsp"])).addMenu();a="Calculator";"ch"==LAN&&(a="\u5b9e\u7528\u8ba1\u7b97");b=["LogP"];"ch"==LAN&&(b=["LogP"]);(new Aciss3.sideToolbarMenu(a,b,["/module/cal_job/cal_job.jsp"])).addMenu();a="History";"ch"==LAN&&(a="\u64cd\u4f5c\u5386\u53f2");
b=["History"];"ch"==LAN&&(b=["\u5386\u53f2\u8bb0\u5f55"]);(new Aciss3.sideToolbarMenu(a,b,["/module/history/history.jsp"])).addMenu();a="Settings";"ch"==LAN&&(a="\u4e2a\u4eba\u8bbe\u7f6e");b=["User Info"];"ch"==LAN&&(b=["\u4e2a\u4eba\u4fe1\u606f"]);(new Aciss3.sideToolbarMenu(a,b,["/module/self_settings/self_user.jsp"])).addMenu()},generateFixedLengthRandom=function(a){for(var b="",c=0;c<a;c++)b+=Math.floor(10*Math.random());return b},generateYearMonthDate=function(){var a=new Date,b=a.getFullYear(),
c=a.getMonth(),c=c+1,c=9>=c?"0"+c.toString():c.toString(),a=a.getDate();9>=a&&(a="0"+a.toString());return b+c+a},generateJobSerial=function(){for(var a=new Date,b=a.getFullYear(),c=a.getMonth(),c=c+1,c=9>=c?"0"+c.toString():c.toString(),d=a.getDate(),a=a.getHours(),e="",f=0;6>f;f++)e+=Math.floor(10*Math.random());return b.toString()+c.toString()+d.toString()+a.toString()+e.toString()};
Aciss3.genRandomFileSerial=function(a){var b=generateJobSerial(),c="";"target"==a?c+="target-"+b:"molecule"==a?c+="molecule-"+b:"gene_cloning"==a?c+="gc-"+b:"protein_reagent"==a?c+="pro-"+b:"protein_reagent_pur"==a?c+="pur-"+b:"assay"==a?c+="assay-"+b:"fbdd"==a?c+="fbdd-"+b:"stru_mounting"==a?c+="struMounting-"+b:"stru_data"==a?c+="struData-"+b:"stru_deter"==a&&(c+="struDeter-"+b);return c};
var Aciss3FilesTabDeleteFile=function(a,b){var c="Delete it?";"ch"==LAN&&(c="\u786e\u8ba4\u5220\u9664\uff1f");$.prompt("<span style='font-size:14px;'>"+c+"</span>",{title:"",buttons:{Yes:!0,No:!1},submit:function(c,e,f,g){e&&(c={},c.document_id=a,$.post(path+"/DeleteDoc",c,function(a){a.success&&(Aciss3.popSuccessNotify(),Aciss3.getCmp("files_grid_"+b).refreshPage())}))}})};Aciss3.FilesTab=function(){this.init.apply(this,arguments)};
Aciss3.FilesTab.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.tab_list=[];this.initFilesTab();Aciss3[this.Id]=this;return this},initFilesTab:function(){var a=this,b=this.main_id,c=this.files_tab,d=this.module,e=this.related_project_id,f=this.related_target_id,g=this.genDocFileOperationStr,h=this.genXlsFileOperationStr,m=this.genOtherFileOperationStr,k=function(a,b,c){return'<div style="word-break:break-all;width:197px;"><a target="_blank" class="detail_info_a_link" style="word-break:break-all;" href="'+
Aciss3.docRootUrl+c.file_path+'">'+b+"."+c.file_ext+"</a></div>"},n=function(a,b,c){b="";b=c.file_ext;return b="doc"==b||"docx"==b?g(a,c):"xls"==b||"xlsx"==b?h(a,c):m(a,c)},l=path+"/module/doc/new_doc.jsp?related_project_id="+e+"&related_target_id="+f+"&related_id="+b+"&module="+d,p=path+"/module/doc/new_xls.jsp?related_project_id="+e+"&related_target_id="+f+"&related_id="+b+"&module="+d,q="Word file (.doc)",r="Excel file (.xls)";"ch"==LAN&&(q="Word \u6587\u6863 (.doc)",r="Excel \u6587\u6863  (.xls)");
var s=$("<div>"),p='<a target="_blank" href="'+p+'" style="color:#000000;cursor:pointer;"><button type="button" class="btn btn-default" style="margin-top:20px;margin-left:10px;"><span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;<i class="fa fa-file-excel-o fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;'+r+"</button></a>";s.append('<a target="_blank" href="'+l+'" style="color:#000000;cursor:pointer;"><button type="button" class="btn btn-default" style="margin-top:20px;"><span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;<i class="fa fa-file-word-o fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;'+
q+"</button></a>");s.append(p);c.append(s);l="<b>Tips</b>: The supported file formats include: doc, docx, xls, xlsx, pdf, sdf, pdb, ab1, seq, txt, jpg, png, zip";"ch"==LAN&&(l="<b>\u63d0\u793a</b>: \u652f\u6301\u4e0a\u4f20\u7684\u6587\u4ef6\u683c\u5f0f\u5305\u62ec: doc, docx, xls, xlsx, pdf, sdf, pdb, ab1, seq, txt, jpg, png, zip");"gene_cloning"==d&&("ch"==LAN?(l+="<br /><b>Gene cloning \u7684\u6587\u4ef6\u540d\u5e94\u5f53\u4ee5\u8d28\u7c92\u7f16\u53f7\u5f00\u5934\u547d\u540d\uff0c\u4f8b\u5982\uff1apEPZ001_xxx.seq\u3002</b><br /><b>\u4e0a\u4f20\u6587\u4ef6\u4e2d\u540e\u7f00\u4e3a.seq\u7684\u6587\u4ef6\u5c06\u76f4\u63a5\u88ab\u8ba4\u4e3a\u662f\u542b\u6709Fasta\u683c\u5f0f\u5e8f\u5217\u7684\u6587\u4ef6\u5e76\u8fdb\u884c\u81ea\u52a8\u89e3\u6790\u3002</b>",
l+="<br /><b>\u4e0a\u4f20\u6587\u4ef6\u4e2d\u540e\u7f00\u4e3a.png\u7684\u6587\u4ef6\u5c06\u76f4\u63a5\u88ab\u8ba4\u4e3a\u8d28\u7c92\u7684\u56fe\u8c31\u6587\u4ef6\u3002</b>"):(l+="<br />The file name of gene cloning should start with Storage No, such as pEPZ001_xxx.seq",l+="<br /><b>The uploaded file with the suffix '.txt'will be considered as a file containing the Fasta format sequence and will be automatically parsed.</b>",l+="<br /><b>The uploaded file with the suffix '.png' will be considered as the map file of the plasmid.</b>"));
l=$('<div style="margin-top:15px;">'+l+"</div>");c.append(l);l=$('<form enctype="multipart/form-data" style="margin-top:30px;">');q="file_upload_input_"+this.main_id;l.append('<input id="'+q+'" class="file" type="file" multiple data-min-file-count="1">');c.append(l);$("#"+q).fileinput({uploadUrl:path+"/SubmitUploadFiles",showUpload:!1,previewFileType:"any",allowedFileExtensions:"doc docx pdf sdf pdb xls xlsx ab1 seq txt jpg png zip".split(" "),maxFileCount:30,minFileCount:1,uploadExtraData:function(){return{main_id:b,
module:d,related_target_id:f,related_project_id:e,doc_comments:$("#doc_comments_"+b).val()}}});$("#file_upload_input_"+b).on("filebatchuploadcomplete",function(){Aciss3.popSuccessNotify();$("#file_upload_input_"+b).fileinput("reset");Aciss3.getCmp("files_grid_"+b).refreshPage()});l="Doc Comments";"ch"==LAN&&(l="\u6587\u4ef6\u5907\u6ce8\u4fe1\u606f");q=$('<div style="margin-top:10px;">');q.append('<div class="row register_prop_row"><div class="col-xs-2"><span>'+l+'</span>:</div><div class="col-xs-4"><input type="text" class="form-control" id="doc_comments_'+
b+'"></div></div>');c.append(q);l="Upload Files";"ch"==LAN&&(l="\u4e0a\u4f20\u6587\u4ef6");l=$('<button class="btn btn-default" type="button" style="margin-top:10px;"><span style="font-weight:bold;color:#0078d7;">'+l+"</span></button>");l.on("click",function(){a.submitFileAction(a.main_id)});c.append(l);var l=$('<div style="margin-top:50px;" id="files_grid_div_'+b+'">'),u=["Document name","Document Comments","Document type","Create user","Operation"];"ch"==LAN&&(u=["\u6587\u6863\u540d\u79f0","\u6587\u6863\u5907\u6ce8",
"\u6587\u6863\u7c7b\u578b","\u521b\u5efa\u7528\u6237","\u64cd\u4f5c\u6309\u94ae"]);c.append(l).each(function(){var a={};a.related_id=b;a.module=d;a.browse_type="all";new Aciss3.baseGrid("files_grid_"+b,{main_div:"files_grid_div_"+b,main_id:"document_id",post_url:"/DocumentBrowse",start:0,page_size:5,submit_params:a,paging_pos:"both",show_column_list:u,column_list:["file_name","file_comments","file_ext","register_user_name","document_id"],widths:[200,160,100,100,140],sorts:["no","no","no","no","no"],
renderers:[k,"","","",n]})})},submitFileAction:function(a){$("#file_upload_input_"+a).fileinput("upload")},genOtherFileOperationStr:function(a,b){var c="",d=b.related_id;return c=b.register_user_id.toString()==USERID?c+('<a class="progress_button" onclick="Aciss3FilesTabDeleteFile('+a+",'"+d+'\')" style="cursor: pointer;"><span class="glyphicon glyphicon-trash"></span></a>'):c+"&nbsp;&nbsp;&nbsp;&nbsp;/"},genDocFileOperationStr:function(a,b){var c="",d=b.register_user_id.toString(),e=b.file_status,
f=b.file_path,g=b.file_serial,h=Aciss3.docServerRootUrl+f,m='<a class="progress_button" target="_blank" href="'+(path+"/module/doc/view_doc.jsp?file_path="+h+"&file_serial="+g)+'"><span class="glyphicon glyphicon-eye-open"></span></a>',k='&nbsp;&nbsp;&nbsp;&nbsp;<a class="progress_button" target="_blank" href="'+(path+"/module/doc/edit_doc.jsp?file_path="+h+"&file_serial="+g+"&register_user_id="+d+"&file_status="+e)+'"><span class="glyphicon glyphicon-edit"></span></a>',g='&nbsp;&nbsp;&nbsp;&nbsp;<a class="progress_button" target="_blank" href="'+
(path+"/module/doc/review_doc.jsp?file_path="+h+"&file_serial="+g)+'"><span class="glyphicon glyphicon-edit"></span></a>',h='&nbsp;&nbsp;&nbsp;&nbsp;<a class="progress_button" onclick="Aciss3FilesTabDeleteFile('+a+",'"+b.related_id+'\')" style="cursor: pointer;"><span class="glyphicon glyphicon-trash"></span></a>',f=f.replace("."+b.file_ext,".pdf"),f='&nbsp;&nbsp;&nbsp;&nbsp;<a target="_blank" href="'+(Aciss3.docRootUrl+f)+'" class="progress_button" style="cursor: pointer;"><span class="glyphicon glyphicon-download-alt"></span>&nbsp;PDF</a>',
c=c+m;0==e&&(c=d==USERID?c+k+h:c+g);1==e&&(d==USERID&&(c+=h),c+=f);return c},genXlsFileOperationStr:function(a,b){var c,d=b.register_user_id.toString(),e=b.file_status;c=b.file_serial;var f=Aciss3.docServerRootUrl+b.file_path,g='&nbsp;&nbsp;&nbsp;&nbsp;<a class="progress_button" target="_blank" href="'+(path+"/module/doc/edit_xls.jsp?file_path="+f+"&file_serial="+c+"&register_user_id="+d+"&file_status="+e)+'"><span class="glyphicon glyphicon-edit"></span></a>',h='&nbsp;&nbsp;&nbsp;&nbsp;<a class="progress_button" onclick="Aciss3FilesTabDeleteFile('+
a+",'"+b.related_id+'\')" style="cursor: pointer;"><span class="glyphicon glyphicon-trash"></span></a>';c=""+('<a class="progress_button" target="_blank" href="'+(path+"/module/doc/view_xls.jsp?file_path="+f+"&file_serial="+c)+'"><span class="glyphicon glyphicon-eye-open"></span></a>');0==e&&d==USERID&&(c=c+g+h);1==e&&d==UserId&&(c+=h);return c}};
var Aciss3GenAttachedFilesList=function(a){var b="";a=a.document_list;for(var c=0;c<a.length;c++){var d=a[c],e=d.module,f=d.file_name,g=d.file_ext,d=Aciss3.docRootUrl+d.file_path,h="Plasmid Map",m="Attached File";"ch"==LAN&&(h="\u8d28\u7c92\u56fe\u8c31",m="\u9644\u5c5e\u6587\u4ef6");h='<div style="margin-top:5px;"><span class="label label-primary" style="font-size:15px;font-weight:normal;">'+h+"</span>&nbsp;&nbsp;";m='<div style="margin-top:5px;"><span class="label label-primary" style="font-size:15px;font-weight:normal;">'+
m+"</span>&nbsp;&nbsp;";b="gene_cloning"==e&&"png"==g?b+h:b+m;b+='<a class="detail_info_a_link" style="word-break:break-all;line-height:25px;" target="_blank" href="'+d+'"><span class="glyphicon glyphicon-download-alt"></span>&nbsp;&nbsp;'+f+"."+g+"</a></div>"}return b},genTrackingTimeLineItem=function(a,b,c){var d=a.progress_id,e=a.progress_date.split(" ")[0],f=a.progress_module,g=Aciss3.getEnumTypeValue(f);return(new Aciss3.TimelineItme("tracking_item_"+b+"_"+d,{tab_module:c,item_date:e,item_module:f,
item_module_show:g,item_user:a.register_user_name,item_target:a.related_target_name,item_target_id:a.related_target_id,item_related_id:a.related_id,item_step:a.progress_step,item_step_comments:a.progress_step_comments,data_name_list:[],data_value_list:[],renderers:[]})).genTimeItemDiv()};Aciss3.genTableTr=function(a,b){b=Aciss3.parseTbCell(b);return"<tr><td width=200><b>"+a+":&nbsp;&nbsp;&nbsp;&nbsp;</b></td><td>"+b.toString()+"</td></tr>"};
Aciss3.genValidateWeightUnitErrorInfo=function(){var a="Please fill g/mg/kg/ug/L/mL/uL";"ch"==LAN&&(a="\u5355\u4f4d\u4ec5\u5141\u8bb8\u586b\u5199 g/mg/kg/ug/L/mL/uL");return a};Aciss3.getWeightIndexByStr=function(a){var b="0";"kg"==a?b="1":"g"==a?b="2":"mg"==a?b="3":"ug"==a?b="4":"L"==a?b="5":"mL"==a?b="6":"uL"==a?b="7":"\u4e2a"==a&&(b="8");return b};
Aciss3.getWeightStrByIndex=function(a){var b="Unknown";1==a?b="kg":2==a?b="g":3==a?b="mg":4==a?b="ug":5==a?b="L":6==a?b="mL":7==a?b="uL":8==a&&(b="\u4e2a");return b};Aciss3.getPriStrByIndex=function(a){var b="Unknown";1==a?b="User":2==a?b="Project leader":3==a?b="Senior leader":0==a&&(b="Supervisor");return b};
Aciss3.filterItems=function(a,b,c){var d=$("#"+b),e=$("#"+c),f=0,g=0,h="name";"ch"==LAN&&(h="ch_name");for(var m=0;m<a.length;m++){var k=a[m];if(null==k[h]||""==h)h="name";var n=$('<div class="col-xs-1">'+k[h]+":</div>"),l=k.type,p=k.collapse;"text"==l?(l=$('<div class="col-xs-3"><input type="text" class="form-control" id="'+k.id+'_search"></div><div class="col-xs-2"><input data-on-text="Fu"  data-off-text="Ac" data-on-color="retroorange" type="checkbox" name="bioassay-filter-checkbox" checked id="'+
k.id+'_search_type"></div>'),!1==p?(d.append(n),d.append(l),f+=1,0==f%2&&d.append('<div class="clearfix"></div>')):!0==p&&(e.append(n),e.append(l),g+=1,0==g%2&&e.append('<div class="clearfix"></div>'))):"matchCombo"==l?(l=$('<div class="col-xs-5"><div id="'+k.id+'_search" style="width:89%"></div></div>'),!1==p?(d.append(n),d.append(l),f+=1,0==f%2&&d.append('<div class="clearfix"></div>')):!0==p&&(e.append(n),e.append(l),g+=1,0==g%2&&e.append('<div class="clearfix"></div>')),new Aciss3.matchCombo(k.id+
"_search_combo",k.param)):"date"==l?(l="To","ch"==LAN&&(l="\u81f3"),l=$('<div class="col-xs-2"><input class="form-control form_date" type="text" value="" id="'+k.id+'_begin_search" data-date="" data-date-format="mm/dd/yyyy" style="background-color:#fff;width:130px;" placeholder="Input Date"></div><div class="col-xs-3 font-gray" style="padding-left:12px;"><span>'+l+':&nbsp&nbsp&nbsp&nbsp</span><input class="form-control form_date" type="text" value="" id="'+k.id+'_end_search" data-date="" data-date-format="mm/dd/yyyy" style="background-color:#fff;width:130px;display:inline-block;" placeholder="Input Date"></div>'),
!1==p?(d.append(n),d.append(l),f+=1,0==f%2&&d.append('<div class="clearfix"></div>')):!0==p&&(e.append(n),e.append(l),g+=1,0==g%2&&e.append('<div class="clearfix"></div>'))):"int"==l||"float"==l?(l="To","ch"==LAN&&(l="\u81f3"),l=$('<div class="col-xs-2"><div class="input-group spinner" data-trigger="spinner" style="width:130px;"><input id="'+k.id+'_begin_search" type="text" class="form-control text-center input-sm" value="" data-rule="quantity"><div class="input-group-addon"><a onClick="NumberInputPlus(this)" class="spin-up" data-spin="up"><i class="fa fa-caret-up"></i></a><a onClick="NumberInputMinus(this)" class="spin-down" data-spin="down"><i class="fa fa-caret-down"></i></a></div></div></div><div class="col-xs-3 font-gray" style="padding-left:12px;"><span>'+
l+':&nbsp&nbsp&nbsp&nbsp</span><div class="input-group spinner" data-trigger="spinner" style="width:130px;display:inline-block;"><input id="'+k.id+'_end_search" type="text" class="form-control text-center input-sm" value="" data-rule="quantity" style="width:111px;float:none;"><div class="input-group-addon" style="width:19px;float:right;"><a onClick="NumberInputPlus(this)" class="spin-up" data-spin="up"><i class="fa fa-caret-up"></i></a><a onClick="NumberInputMinus(this)" class="spin-down" data-spin="down"><i class="fa fa-caret-down"></i></a></div></div></div>'),
!1==p?(d.append(n),d.append(l),f+=1,0==f%2&&d.append('<div class="clearfix"></div>')):!0==p&&(e.append(n),e.append(l),g+=1,0==g%2&&e.append('<div class="clearfix"></div>'))):"staticCombo"==l&&(l=$('<div class="col-xs-5"><div id="'+k.id+'_search" style="width:89%"></div></div>'),!1==p?(d.append(n),d.append(l),f+=1,0==f%2&&d.append('<div class="clearfix"></div>')):!0==p&&(e.append(n),e.append(l),g+=1,0==g%2&&e.append('<div class="clearfix"></div>')),new Aciss3.staticCombo(k.id+"_search_combo",k.param))}0<
g&&$("#filter_collapse_button").css("display","inline-block");$("#"+b+" [name='bioassay-filter-checkbox']").bootstrapSwitch();$("#"+c+" [name='bioassay-filter-checkbox']").bootstrapSwitch();$("#"+b+" .form_date").datetimepicker({weekStart:1,todayBtn:1,autoclose:1,todayHighlight:1,startView:2,minView:2,forceParse:1});$("#"+c+" .form_date").datetimepicker({weekStart:1,todayBtn:1,autoclose:1,todayHighlight:1,startView:2,minView:2,forceParse:1})};
Aciss3.filterParams=function(a){for(var b={},c="",d="",e="",f=0;f<a.length;f++){var g=a[f],h=g.type;"text"==h?(b[g.id]=$("#"+g.id+"_search").val().trim(),h=$("#"+g.id+"_search_type").bootstrapSwitch("state"),h=!0==h?0:1,b[g.id+"_search_type"]=h,d+="@@"+g.id,e+="@@string",c=void 0!=g.column_class?c+("@@"+g.column_class):c+"@@0"):"matchCombo"==h?(b[g.id]=Aciss3.getCmp(g.id+"_search_combo").getValue(),d+="@@"+g.id,e+="@@enum_int",c=void 0!=g.column_class?c+("@@"+g.column_class):c+"@@0"):"date"==h?(b[g.id+
"_begin"]=$("#"+g.id+"_begin_search").val(),b[g.id+"_end"]=$("#"+g.id+"_end_search").val(),d+="@@"+g.id,e+="@@"+h,c=void 0!=g.column_class?c+("@@"+g.column_class):c+"@@0"):"int"==h||"float"==h?(b[g.id+"_begin"]=$("#"+g.id+"_begin_search").val(),b[g.id+"_end"]=$("#"+g.id+"_end_search").val(),d+="@@"+g.id,e+="@@"+h,c=void 0!=g.column_class?c+("@@"+g.column_class):c+"@@0"):"staticCombo"==h&&(b[g.id]=Aciss3.getCmp(g.id+"_search_combo").getValue(),d+="@@"+g.id,e+="@@enum_int",c=void 0!=g.column_class?
c+("@@"+g.column_class):c+"@@0")}c=c.slice(2);d=d.slice(2);e=e.slice(2);b.search_class_column_str=c;b.search_column_str=d;b.search_type_column_str=e;return b};function NumberInputPlus(a){a=$(a).closest("div[class*='spinner']").find("input");var b=Number($(a).val()),b=b.add(1);$(a).val(b);$(a).trigger("onchange")}function NumberInputMinus(a){a=$(a).closest("div[class*='spinner']").find("input");var b=Number($(a).val()),b=b.sub(1);$(a).val(b);$(a).trigger("onchange")}
Aciss3.MultiSelect=function(){this.init.apply(this,arguments)};
Aciss3.MultiSelect.prototype={init:function(a,b){for(var c in b)this[c]=b[c];this.Id=a;this.value=[];this.show_value=[];this.delete_list=[];this.add_list=[];this.initMultiSelect();Aciss3[this.Id]=this;return this},initMultiSelect:function(){this.multi_select_div=$('<div id="'+this.Id+'" class="multi_select_show_div"></div>');var a=$('<div class="alert alert-warning" contenteditable="true" style="display:inline-block;margin:2px 0 2px 5px;padding:3px;">No Data</div>'),b=this;$("#"+this.matchcombo_id+
"_input_hidden").bind("change",function(){var a=Aciss3.getCmp(b.matchcombo_id).getValue(),d=Aciss3.getCmp(b.matchcombo_id).getShowValue();$("#"+this.Id+" .alert-warning").remove();b._addProjectMember(a,d)});this.multi_select_div.append(a);$("#"+this.main_div).append(this.multi_select_div)},setValue:function(a){this.multi_select_div.empty();this.value=[];this.show_value=[];var b=this;if(0==a.length)a=$('<div class="alert alert-warning" contenteditable="true" style="display:inline-block;margin:2px 0 2px 5px;padding:3px;">No Data</div>'),
b.multi_select_div.html(a);else for(var c=0;c<a.length;c++){var d=a[c],e=d[0],d=d[1],f=$('<div class="alert alert-info" contenteditable="true" style="display:inline-block;margin:2px 0 2px 5px;padding:3px;" id="'+this.Id+"_laber_"+e+'">'+d+"</div>"),g=$('<button type="button" class="close" data-dismiss="alert">\u00d7</button>');f.append(g);g.on("click",function(a){return function(){b._addDeleteList(a)}}(""+e));b.value.push(""+e);b.show_value.push(""+d);b.multi_select_div.append(f)}},getValue:function(){return this.value},
getShowValue:function(){return this.show_value},reset:function(){this.value=[];this.show_value=[];this.delete_list=[];this.add_list=[];this.multi_select_div.empty();var a=$('<div class="alert alert-warning" contenteditable="true" style="display:inline-block;margin:2px 0 2px 5px;padding:3px;">No Data</div>');this.multi_select_div.append(a)},_deleteAddedList:function(a){var b=$.inArray(a,this.add_list);0<=b&&this.add_list.splice(b,1);a=$.inArray(a,this.value);0<=a&&(this.value.splice(a,1),this.show_value.splice(a,
1))},_addDeleteList:function(a){0>$.inArray(a,this.delete_list)&&this.delete_list.push(a);a=$.inArray(a,this.value);0<=a&&(this.value.splice(a,1),this.show_value.splice(a,1))},_addProjectMember:function(a,b){$("#"+this.Id+" .alert-warning").remove();var c=this;0>$.inArray(a,this.value)&&(c.value.push(a),c.show_value.push(b));if(0<=$.inArray(a,c.delete_list)){var d=$.inArray(a,c.delete_list);c.delete_list.splice(d,1)}if(0==$("#"+this.Id+"_laber_"+a).length&&0>$.inArray(a,c.add_list)){var d=$('<div class="alert alert-info" contenteditable="false" style="display:inline-block;margin:2px 0 2px 5px;padding:3px;" id="'+
this.Id+"_laber_"+a+'">'+b+"</div>"),e=$('<button type="button" class="close" data-dismiss="alert">\u00d7</button>');d.append(e);e.on("click",function(a){return function(){c._deleteAddedList(a)}}(a));c.multi_select_div.append(d);c.add_list.push(a)}}};
var genGridSortCombo=function(a,b){for(var c=[],d=0;d<a.length;d++){var e=a[d],f=e.id,g=e.name;"ch"==LAN&&(g=e.ch_name);e=e.column_class;void 0==e&&(e="0");c.push([f+"@@"+e,g])}new Aciss3.staticCombo("grid_order_combo",{main_div:"grid_order_combo_div",data_list:c,req_type:"yes"});$("#grid_desc_label").on("click",function(){var a=Aciss3.getCmp("grid_order_combo").getValue();if(null==a)alert("Please select sort column");else{var a='{"property":"'+a+'","direction":"DESC"}',c=Aciss3.getCmp(b).getSubmitParams();
c.sort=a;Aciss3.getCmp(b).setSubmitParams(c);Aciss3.getCmp(b).start=0;Aciss3.getCmp(b).refreshPage();"ch"==LAN?$("#now_show_grid_sort_label").html("\u964d\u5e8f"):$("#now_show_grid_sort_label").html("DESC")}$(".dropdown-toggle").dropdown("toggle");return!1});$("#grid_asc_label").on("click",function(){var a=Aciss3.getCmp("grid_order_combo").getValue();if(null==a)alert("Please select sort column");else{var a='{"property":"'+a+'","direction":"ASC"}',c=Aciss3.getCmp(b).getSubmitParams();c.sort=a;Aciss3.getCmp(b).setSubmitParams(c);
Aciss3.getCmp(b).start=0;Aciss3.getCmp(b).refreshPage();"ch"==LAN?$("#now_show_grid_sort_label").html("\u5347\u5e8f"):$("#now_show_grid_sort_label").html("ASC")}$(".dropdown-toggle").dropdown("toggle");return!1})};
$(function(){loadSideToolBar();"ch"==LAN?$("#lan_label").html("English"):"en"==LAN&&$("#lan_label").html("\u4e2d\u6587");for(var a=0;a<$(".modal").length;a++){var b=$(".modal")[a];$(b).children(":first").hasClass("modal-dialog")&&$(b).css("background-color","transparent")}Aciss3.loadingStr="Running. Please wait....";"ch"==LAN&&(Aciss3.loadingStr="\u8fd0\u884c\u4e2d\uff0c\u8bf7\u8010\u5fc3\u7b49\u5f85....")});
